### ISSUE TITLE
Missing vagga-suttas headings in search results

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1054]
In eg. the following searches:
https://suttacentral.net/search?query=pariccāga
https://suttacentral.net/search?query=foremost laywoman
results for vagga-suttas do not have titles.

**Comment by SamaneriVimala** [comment]
I suspect this is the same bug as why the suttaplex titles disappeared: this only happens in AN texts (and maybe SN) where there is a range because the title contains a hidden symbol. See for instance `/an1.258-267/en/sujato`. This needs to be fixed in the extraction of the po files.
I can possibly mask this, but that is not a permanent solution. I will make a new ticket for taking care of this problem.
