### ISSUE TITLE
Intergrating SuttaCentral Voice Assistant

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#1136]
Further to the release of the [SuttaCentral Voice Assistant v0.2.4](https://discourse.suttacentral.net/t/suttacentral-voice-assistant-v0-2-4/10676) and a meeting with developer Karl Lew we've agreed that the first steps towards intergrating this funtionality with the main SuttaCentral site is to link the audio URLs into the suttaplex cards. 

The meeting covered:

1) **direct hosting** would be easy on an Ubuntu 16.04 system with 10-100GB of disk storage.  The only thing needed is an AWS Polly account. Karl can update Github with instructions if required.
2) **cloud hosting** is already being done on AWS with the Elastic IP of http://50.18.90.151/. Anybody can host SC-Voice on any AWS EC2 account. It currently occupies a T2 micro instance, but may need more disk given all the requirements for sound storage. This is especially true when supporting multiple voices and languages. MN1 alone consumes about 25MB for a single voice.
3) **offline hosting** is also possible when provisioned with sound. We can put SC-Voice on a Raspberry Pi and have it provide the web-page anywhere in the world since the RPi can be its own web server. Amongst other things this could be of particular use for monestaries with limited intented access. 
4) **content integration via GitHub** is one way to enlarge SC-Voice scope beyond Bhante Sujato's translation repo. I understand Pootl files are vanishing, but we could just share JSON files in some hierarchy that includes translator as well as language. This is an unusual suggestion for integration, but it may be valuable to have an SC  JSON repository and/or REST service to promote broader dissemination of content.
5) **content integration via REST** is another way to integrate SC-Voice with SuttaCentral. Right now it just needs JSON like this: [http://50.18.90.151/scv/sutta/mn1/en/sujato](http://50.18.90.151/scv/sutta/mn1/en/sujato)
6) **other languages** are very possible. It should be easy to add Pali voice with interleaved en/pli spoken by Amy/Raveena.  In addition, we can move into other languages such as German, etc., with help from native speakers.
7) **URL integration** is the easiest way to integrate quickly with ongoing SC site ui work. The resulting infrastructure is a bit fragile since it is not centrally maintained by a group. I would only recommend that for short term integration as we explore a more robust solution that doesn't require me to fix things.

Other points also raised include:

* The intention to back the audio up on archive.org once any remaining issues with the files have been ironed out.
* Drawing in human read suttas from http://audtip.dx.am/ and https://www.paliaudio.com/   
* The possibility of using the Github for large files fascility. 
* Periodically refreshing the source data so that as corresions are made and new (corrected) audio will be generated.

## Next steps: 

* Karl is working on the URL documentation 
* The SC devs need to figure out adding in an audio icon to the suttaplex cards.

**Comment by firepick1** [comment]
We need a way to share IT administration and development. With declining vision, I do not know how much longer I will be able to help personally. At some point I will simply become an SC-Voice user happily listening to suttas. With this in mind, I will need some guidance as to documentation requirements for reproducing, maintaining and developing SC-Voice. The initial environment of Ubuntu 16.04 simply reflects what I have on my desk. It is a Chromebook with crouton. Similarly, the AWS environment was simply the first working cloud host explored. I tried Joyent/Triton and it was not capable enough.  Also, the recent advances in Google's own voice capability may be of interest to others to pursue. SC-Voice is designed for TTS service plug-ins. Others can certainly plug in WaveNet or whatever arises. 

My own priorities are to create something workable quickly. This urgency is driven by impending disability alone. That urgency may also lead to peculiar actions such as putting SC-Voice on a Raspberry Pi so that I can carry it around. I likely do not have time to learn the skills to create an iPhone app, for example. If others have such skills to pursue SuttaCentral priorities, please volunteer! My skills are limited.

**Comment by Aminah-SC** [comment]
Brilliant! Thanks so much!
