### ISSUE TITLE
Green hosting

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1296]
#### User story

I want to use website without destroying the world!

#### Feature description

We should use green hosting, currently, it seems, we do not.

https://www.thegreenwebfoundation.org/ 

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by blake-sc** [comment]
Well, we are hosted in Fremont, CA (that site wont detect that because Cloudflare) where the carbon per kWh is quite low. Power usage amounts to about 10 W which is about 90 kWh per year which would be about 25 kg of CO2 per year using general numbers for CA electricity, or about the same as the CO2 emissions from burning 10L of petrol.

Using "green" hosting would be at best a feel good gesture and it would just be stupidity to feel good about it. VPS computing is very energy efficient, the VPS we host on - and a VPS is a small slice of a real server - has less computing power than a typical laptop and would use less energy because it's headless.

I searched "Green Hosting" and at the top of the list were GreenGeeks.com who proudly proclaim:

    All WordPress hosting account usage is offset by 300% in renewable energy credits!

Which probably costs them like $1/year!

The carbon credits to offset our hosting would cost like 50c per year.
