### ISSUE TITLE
Get SC added to app stores

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1339]
#### User story

Fred wants to read some suttas. She checks the app store on her phone, but only gets crappy old stuff. Where is the shiny new thing? It lives on the Wild West Web! So she doesn't even know it exists.

#### Feature description

PWAs are now accepted on the Google Play store:

https://medium.com/@firt/google-play-store-now-open-for-progressive-web-apps-ec6f3c6ff3cc 

We should investigate IPhone app store too, and any other relevant places.

#### Acceptance criteria (the list of things that need to be done for the ticket to be considered finished):

Phone/tablet users can find and install SC as a PWA through their app store.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by michaelh-sc** [comment]
An initial Android TWA app is up at:


 [https://github.com/michaelh-sc/suttacentral-android-twa-app](https://github.com/michaelh-sc/suttacentral-android-twa-app)

At time of writing, this runs if you install Chrome Dev - it shouldn't be long until this is in production releases. 

**Some sub-dependencies under External Dependencies:**

* Logic of how TWA generally opens on phones without latest Chrome is unclear
* Whether Chrome really is bundled and kept up to date in all recent Android releases.


**Other Play Store Dependencies:**

* Passes Lighthouse test ([https://developers.google.com/web/tools/lighthouse/]([https://developers.google.com/web/tools/lighthouse/))
* All of the Play Store Prerequisites [https://developer.android.com/distribute/best-practices/launch/launch-checklist](https://developer.android.com/distribute/best-practices/launch/launch-checklist)
  - Developer account
  - Preserve app state
  - Play store listing summary etc.
  - Testing against a range of tablets and devices. AWS Device Farm no longer has newer devices
  - Content policy double-check https://play.google.com/about/developer-content-policy


**Functionalities tested:**

* Project builds without errors
* Produced code for presumed functionalities
  - Offline files download
  - Splash screen with SC logo on load and same colour scheme as WebAPK
  - Takes links for SuttaCentral
  - Load time is same as WebAPK
  - Testing on WebAPK also applicable to this.


**Suggested possible functionalities to pass:**

* Clash/same name as WebAPK (Add to Home Screen) and Offline Files need re-download.
  - Naming the launcher differently will help - currently I have named it "SuttaCentral TWA" . Also, the address bar has re-appeared on the WebAPK for some reason after testing but I can't remember if this was always there or whether we want this to stay :)
* Other languages for App Store name and metadata
* Behaviour on Samsung browsers and devices with no updated Chrome must be tested
* SuttaCentral D&D App
* Automated testing on a range of devices

**Nice to haves:**

* Push Notifications are allowable under TWA in Play Store. This could be used for status of Offline downloads or D&D notifications (see https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications ) .
* Pre-loading navigation bars on first launch (there is a delay on load, and also navigation bars seem to still come out with Network missing when I turn off data).
* The WebAPK displays the loading splash screen while the page is actually loading whereas this doesn't. There might be a way to notify on finished loading that matches.
* Somehow point the Offline Files for WebAPK to TWA so there is no clash

There is a release .apk in app/release signed with a key I've kept securely. The app points to https://staging.suttacentral.net . Next step for further testing I'd like to request is to put the following at https://staging.suttacentral.net/.wellknown/assetlinks.json : 

[https://raw.githubusercontent.com/michaelh-sc/suttacentral-android-twa-app/master/app/assetlinks.json so that this can be distributed for testing](https://raw.githubusercontent.com/michaelh-sc/suttacentral-android-twa-app/master/app/assetlinks.json so that this can be distributed for testing)


**Further Reading**

Google Docs on TWA [https://developers.google.com/web/updates/2019/02/using-twa]([https://developers.google.com/web/updates/2019/02/using-twa)

Google Example TWA App svgomg: [https://github.com/GoogleChromeLabs/svgomg-twa](https://github.com/GoogleChromeLabs/svgomg-twa)

CustomTabs Source [https://github.com/GoogleChrome/custom-tabs-client/tree/master/customtabs](https://github.com/GoogleChrome/custom-tabs-client/tree/master/customtabs)

Google Doc Custom Tabs [https://developer.chrome.com/multidevice/android/customtabs] (https://developer.chrome.com/multidevice/android/customtabs)

**Comment by chansikpark** [comment]
@michaelh-sc: Wow, this is great work! I've just started taking a look at this stuff, and you've pointed out a lot of things that I didn't think of or was aware of. 

In regards to the assetlinks.json file, I don't have access to the servers, but I've been curious to know, and if you've got a developer account maybe you can test this for us: does the Google Play Store prohibit upload of TWA apps that fail the Site-to-App validation? There's documentation that says that this will just lead to the address bar showing in the app, but there have also been hints that the Google Play Store might evolve to something stricter.

My thinking is that if SuttaCentral is eventually going to start hosting the assetlinks.json, it should also manage the signing and release of the APK as well. But if app developers can be completely independent, that might go a long way to reducing the development burden.

**Comment by michaelh-sc** [comment]
@chansikpark  Hi Chan, thanks so much! I'm unsure if it will be accepted or not without the .well-known/assetlinks.json there - there is a reason for the "Trusted" in TWA I think, I read on blogs it doesn't let you upload a TWA without but I'll try shortly. 

I think the main point is to verify apps and web server through the same signing keys as Play Store in both directions, but no security implications for the server unless you allow sharing saved creds between browser and TWA (which you can do) . You can revoke asst links here either in the assetlinks google page or by removing from the .json: https://developers.google.com/digital-asset-links/v1/revocation - it seems TTL is 8 days though. Other implications of site associations here: https://developer.android.com/training/app-links/verify-site-associations#multiple-apps 

It might suffice for SC core devs/blake to just control the assetlink and have super admin on Play Store + build key but not be responsible for builds/releases. It should be same person/group, with builds verified by a few people, I should think.
