### ISSUE TITLE
Make language pseudo-icons in sidebar show at proper levels

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1375]
## Description:

On sujato-work branch I have made a first pass at getting pseudo-icons working in sidebar:

https://github.com/suttacentral/suttacentral/commit/22eb2e8bdb21a68801353731325c8b9264ae25f7

However, the icons do not show up correctly, as I cannot understand the logic.

Sometimes they display "null" or "undefined", and sometimes they appear where they should not.

## Steps to reproduce:

Checkout sujato-work, look at sidebar.

## Expected behaviour:

The pseudo-icons must appear in exactly the same places with exactly the same content as the svg-language icons.

## Screenshots:

![screenshot from 2019-02-22 10-27-54](https://user-images.githubusercontent.com/6112010/53208886-a13d9600-368c-11e9-8eed-afafeab17bca.png)

**Comment by SamaneriVimala** [comment]
Just a few hints:
You have taken out the code that starts with `${childItem.lang_iso ? html`
That is the code that checks if a language code actually exists. So that is why you get 'null' for Dharmapadas because there is no language code: the language codes should be on the next level. You can see on the main site there is no svg in front of Dharmapadas.

Then you have added the pseudo-element to the link, while before it was a separate element that was placed before the link, if it existed. So now you would need to have two possible links, one with and one without the pseudo-element something like:

If (childItem.lang_iso) exists:
   Then use the link with the pseudo-element
Else use the link without it.

Or alternatively you use the all previous code and just replace the `<iron-icon>` with a `<div>` or `<span>`. I think that is what I would do because it saves a lot of problems.

I suspect by taking out all the checkings you also get the "undefined" ones in there but I have not looked that far. I think the above should give enough of a hint on what you need to look for.

And just to be a pain because Hubert trained me: mind your indentations in the css.

**Comment by ihongda** [comment]
I've tweaked the code a little bit, and it looks something like this:
![Snipaste_2019-03-30_09-56-28](https://user-images.githubusercontent.com/4037966/55269770-1f1b3f80-52d2-11e9-8127-fd95c075b107.png)

**Comment by sujato** [comment]
It works, apart from a bug in the "Dhammapadas"
