### ISSUE TITLE
Add Pali concordance data to bilara-data/reference

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1504]
Following completion of 

https://github.com/suttacentral/suttacentral/issues/1094

The various pali concordance references are now in one convenient file.

https://github.com/suttacentral/sc-data/blob/master/misc/all_pali_concordance.json

This should be imported to bilara-data/reference. The references are keyed off the bilara segment IDs and must be matched to them.

- On import, discard `sc` and `msdiv` numbers, they do not add any value.
- Import should be testy: reject any references that do not exactly match existing segment IDs. We can figure out why and fix it.
- These references will be used in the new text pages that Hongda is building.

**Comment by chansikpark** [comment]
Continuing to work through cleaning up the concordances prior to import, and here proposing a tweak to the reference format, namely in regards to two editions–`bj` (Buddhajayanti) and `cck` (Chulachomklao).

In the migration from the original `pali_concord.json`, there were references containing slashes that were either flattened or dropped altogether. For `bj`, some of the volumes of this edition have two separate "parts" and the data migration appears to have just flattened references to multi-part volumes, which has resulted in hundreds of duplicate references. For example: `bj2/1.2` and `bj2/2.2`, which refer to two very different pages, seem to have become simply `bj2.2`, which is strictly speaking ambiguous because the second volume of the Buddha Jayanthi Tipitaka, is divided across two books, or parts, each having a page number 2. For `cck`, it appears that slash-containing references were dropped altogether. This is evidenced by there being no references to volumes 22 and 23 (which point to AN 5-9) in `all_pali_concordance.json` aot. `pali_concord.json`.

More formally, the original `pali_concord.json` file mapped the triple (Mahasangiti book id, Mahasangiti segment number, Edition id) to the couple (volume #, page #). Volume # is either an empty string, a simple number, or two numbers separated by a slash (eg. "22/2"). The last case occurs only in `bj` and `cck`, and was more or less dropped in the migration to `all_pali_concordance.json`.

***

The question is most generally: assuming that this wasn't intentionally done, how should it be resolved? More specifically, I can think of three different ways to disambiguate: which would be advisable?

Namely,

**(A)** Renumber volume numbers for the given editions so that `bj` goes from having 53 to 60 different volumes and `cck` from 39 to 42 (or 43). So `bj2/1.2` remains `bj2.2`, `bj2/2.2` becomes `bj3.2`, `bj3.2` becomes `bj4.2` and so on. I imagine that this would require an additional map that informs the front end of the real volume numbers, and so is an undesirable solution. On the other hand, this maintains the simple "grammar" for these references.

**(B)** Use dot-notation. `bj2/1.2` becomes `bj2.1.2`. I'm inclined to believe that this is the most logical solution. The front end would be able to deduce the meaning without any additional lookup.

**(C)** Retain the slashes from the old data. This would achieve the same, but add another special character to the grammar. Maybe there was some important reason for it being a slash in the first place..?

***

A bit of a wrench in all this with `bj` is that a null volume refers to the Milindapanha (eg `bj.2`, `bj.3`, etc.). I couldn't find a copy of the BJT's Milindapanha (which allegedly exists according to [GRETIL](http://gretil.sub.uni-goettingen.de/gretil.html#PParCan)) and so it's unclear whether there is a natural sequence number by which the Milindapanha volume fits with the other volumes. Being merely paracanonical, it seems to be excluded in [this](https://www.mediafire.com/folder/oo8eet91ax8py/%E0%B6%B6%E0%B7%94%E0%B6%AF%E0%B7%8A%E0%B6%B0_%E0%B6%A2%E0%B6%BA%E0%B6%B1%E0%B7%8A%E0%B6%AD%E0%B7%92_%E0%B6%AD%E0%B7%8A%E2%80%8D%E0%B6%BB%E0%B7%92%E0%B6%B4%E0%B7%92%E0%B6%A7%E0%B6%9A%E0%B6%BA) listing linked rather authoritatively from the 5.8GB item [here](https://pitaka.lk/books/). 

Leaving it empty goes against the pattern of globally unique references having non-null volumes...

`bj0.2`? `bj53.2`? `bjmil1.2`? `gretil2.2.4.2`?

**Comment by chansikpark** [comment]
I include here a report summarizing duplicate references in `all_pali_concordance.json` by edition and volume as at the current commit level of sc-data/master:

[edition_dupes_6e5d459.pdf](https://github.com/suttacentral/suttacentral/files/3797503/edition_dupes_6e5d459.pdf)

The first handful of entries with empty editions will go away with an autofix. I'll perhaps generate one of these reports with every pull request for the larger changes going forward.

**Comment by sujato** [comment]
This is great sleuthing, and really well explained. Let me make a few comments here.

Excellent work with the BJT deduping. May I suggest, however, that in the case of multi-part “volumes” we use an alphabetic notation, which seems to fit better with normal reference conventions:  Vol 2a, Vol 2b, etc. So `bj2/1.2` would be (I think) `bj2a.2`.

Regarding the listing of the Milinda in the BJT, perhaps this has occurred due to the fact that the Milinda is generally said to be canonical in Myanmar but not in Sri Lanka. It would not be surprising to find that the Sinhalese wanted to make an edition of it, but were coy about including it in the Pitaka per se. We know the people behind the sites that you link to, and they will be much more familiar with the BJT. Let me ask them and see what they suggest.

>for all references with a null volume value (maku is another), if the reference has a dot before a number, it's a page number for a volume that corresponds with the book specified by the segment identifier. 

Right, this seems reasonable.

>If the reference does not have a dot but has a null volume value, namely msdiv, sc, vnp and a subset of pts-vp-pli references, they refer to segments or verses instead of page number.

`msdiv` is I guess a sort of “segment”, but I’d prefer to call it a “section”. It is a reference system used in the Mahasangiti edition that parallels the `ms` numbers. I am not sure what the reason is for using two systems at once, but it must have served some purpose internally for the MS edition. However for our purposes, we use the `ms` numbers, as these are truly unique GUIDs, and all parallels and references to Mahasangiti edition should use these rather than `msdiv`. For now, we retain `msdiv` numbers as a legacy reference in case they may be useful, but it would probably be best to *not* port them over to to the`bilara-data/reference` files, as the doubling of references just adds unnecessary complication.

`sc` numbers are, for the record, usually a straight paragraph count from the beginning of the file, intended as a backup where no more established system is found. We should eliminate them from the cross-reference data, as they will ultimately just duplicate the information of the segment ID.

**Comment by chansikpark** [comment]
> May I suggest, however, that in the case of multi-part “volumes” we use an alphabetic notation, which seems to fit better with normal reference conventions...

Will do, sir.

> It would not be surprising to find that the Sinhalese wanted to make an edition of it, but were coy about including it in the Pitaka per se.

There *is* a book with a title that seems to contain the word 'Milindapanha' that is side by side with the 57-book canon in the Tripitaka section of their listing of books (the 14 MB file [here](https://tipitaka.lk/books/)). However, it looks to be a commentary: the page numbers don't line up, and the very first words in verse (ie. "Milindo nāma so rājā...") appears only interleaved between prose that reads like commentary on the second page. 

Notably, all this was determined by leveraging some OCR built in to Google Docs; opening an image or PDF in Google Docs appears to trigger it, producing digitized text that can then be plugged into Google Translate.

The page numbers in the concordance do, however, line up with what's found in the digitized version available on GRETIL. And while the description there does call it the "BJT edition (input by the Sri Lanka Tripitaka Project)", in the actual file, the page numbers are labelled "[SL Page 001]" etc. while for example in the Patthana, the page numbers are labelled "[BJT Page 001]".

> We know the people behind the sites that you link to, and they will be much more familiar with the BJT. Let me ask them and see what they suggest.

😮

> `msdiv` is I guess a sort of “segment”, but I’d prefer to call it a “section”.

Duly noted, sir. I actually do hope to get some more correction on the terminology I employ for the various concepts under discussion. I've "gisted" [here](https://gist.github.com/chansikpark/e914cfe90a1af495460a91f318b1efce) some regular expressions I've derived decorated with named groups to hopefully make them more readable. Hoping to get your or Blake's impressions/review/etc. (@blake-sc).

**Comment by sujato** [comment]
Just to say, I have heard back from our Sri Lankan friends, they confirm that the Milinda was *not* officially part of the BJT. It seems it must have been published as a supplement of sorts.

I propose that we adopt a convention of using a suffix `-x` to notate this and and similar cases that may come up. We use `-a` to denote “atthakatha” (i.e. commentary) eg `mn-a`, so we can similarly use `-x` to denote “extension or supplement or appendix”. 

Thus the Milinda could be noted as `bj-x`, and if it is a multi-part volume, then `bj-xa`. Do you think that would serve?

If we adopt this, we should make sure it is noted in the relevant places: the abbreviations page, the uid_expansion files, maybe elsewhere.

**Comment by chansikpark** [comment]
> Thus the Milinda could be noted as bj-x, and if it is a multi-part volume, then bj-xa. Do you think that would serve?

Bhante, I would actually counter that if the Milinda were published in a multi-part volume, it would be better off as `bj-x1`, `bj-x2`, etc. This would avoid any potential ambiguity between, eg, some artifact with uid 'xa'.

**Comment by sujato** [comment]
Okay, that should be fine.
