### ISSUE TITLE
Gingerbread Navigation

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1673]
## Background

Primary navigation on SC is via a sidebar. However this has proven unwieldy, as we need too much information to make the navigation meaningful. To solve this, use cards as primary navigation, supported by breadcrumbs.

This issue was explored in a Discourse thread. 

https://discourse.suttacentral.net/t/rethinking-sc-navigation-the-gingerbread-edition/16087

For now I keep the main screenshots and files there, to avoid duplicating. They may evolve over time! 

In this epic I will focus mainly on functionality. Styling is generally as per mockups, and I will tweak it personally.

## Overview

- The Home page provides the main entry point to navigation via cards (nav cards)
- The nav cards are basically the same as the suttaplex cards, except they are customized per context.
- The app toolbar is doubled: a universal toolbar containing breadcrumbs, and a contextual toolbar with information per page.

## Replaces

Replaces the following actual or planned features:

- sidebar (including bug #1363 #1348 
- responsive design to handle sidebar.
- Adaptive Tab Bar (atb) #1494 #1450 #1238 #1496 
   - Note, the ATB remains in use for static pages, it just won't be extended further.
- supertitles as links #1322

**Comment by aminah-sc** [comment]
Further to discussion elsewhere during which I was invited to give some feedback on site navigation, I'm adding some impressions I sketched during a walk through. As both my comments and this ticket are pitched at an overview level, it seemed the best place.

A couple of preliminary notes:
- The primary consideration in mind when exploring the site was how to make the glorious, but wildly sprawling body of material it contains accessible to those with little familiarity with the EBT.
- The walk through reported here was done "blind", ie, with (almost) no reference to other discussion/tickets. While I'm sorry for any repetition that may result from this, I elected this approach as I didn't want to be informed by any assumed working logic, but rather just account for my experience of how easily I understood the material being presented. 
- I very much appreciate this is still a work in progress and that some things mentioned may just known items that just haven't been handled yet; please set any such points aside. 

##  Home

Overall this is an excellent improvement. All the same, these were a couple of points that struck me:

- Thinking especially of the person who lands on the site with very little familiarity of the texts, I feel it could be helpful to give an even clearer signpost as to what can be found on the site by making the division cards a more defined block with a heading.  
- While styling and functionality are in ways separate concerns, there can be places where they overlap and I feel this is one of them. My initial impression was that the division cards  were just elaborate links to the introductory essays and the intention had only been to given the a more prominent position to them to direct new comers. Differentiating a little more through styling may make things clearer. 

   A rough sketch:

   ![961e78df8fcb4072b54255368c8d60df](https://user-images.githubusercontent.com/36522678/92797320-de21c880-f3a9-11ea-8e8c-08a33923fffa.png)

- As an aside, the green tick really isn't the nicest. It would be better to only display the green corner with the language name when there are texts available in the selected language.

## "Basket" level

### Bugs

- Back stepping using browser's back button or a mouse back button doesn't work (tested in FF & Chrome; going back via breadcrumb links does work):

![9dc7695ad06b4b368e838fddb02310ba](https://user-images.githubusercontent.com/36522678/92798741-1d9ce480-f3ab-11ea-9f90-588918012718.png)

- I'm guessing this part of some larger pagination issue, or some such thing (…?):

![91ecfbedf8ec426882f09749d3039a80](https://user-images.githubusercontent.com/36522678/92799421-af0c5680-f3ab-11ea-9669-75aba332895e.png)

<br>

![71f52f5b47ee454aa8b5fb95d873932a](https://user-images.githubusercontent.com/36522678/92799501-c0edf980-f3ab-11ea-813c-f7ea717bb763.png)

### Comments

- My feeling is that each level **needs** a brief blurb explaining its context/contents, and this should be expended by default (perhaps with a toggle button, or also controlled by the "compact view" button) 
- While appreciating the importance of spacial economy I would absolutely prioritize supporting collection understanding / navigability. In turn, I would add "collections" to the second level nav item: `Home > Discourse Collections`
- I'd encourage taking the opportunity to give a drop of extra insight into what comprises the body of texts and say something more like "Collection of Long Discourses from Pali and Chinese traditions", instead of  "Collection of Long Discourses in Pali and Chinese"
- This may just be a temporary loose end, but "Collection of Minor Discourses" and "Collections of Other Discourses" have respectively incomplete and incorrect descriptions. 

## "Nikaya" level

- Again, I feel concise blurbs at every level of the breadcrumb trail would be likely to support users (particularly the new comer, but not just them; there are a number of gaps I still have in my knowledge and I know this is also true of others who've spent a some time actively engaging with the texts), becoming familiar with the overall body of texts. It would perhaps be good to ask if Charles Patton would be interested in writing Agama blurbs to companion the existing ones for the Nikayas. 
- There could be an opportunity to use these and sub-level cards to give a quick view of the hierarchy of a collection and support understanding / familiarity, with a symbiotic relationship with the breadcrumb. A rough sketch:

   ![5a57b8654f9f4201b1612647ce674f95](https://user-images.githubusercontent.com/36522678/92802458-6efaa300-f3ae-11ea-8a81-1befc94071df.png)

## Discourse level

### Bugs (or incomplete)

- When getting to sutta level the breadcrumbs get wiped out. 

   Eg, all good up until the vagga level:

   ![f76c7ac14a2c4340bb6191f924fe9a3b](https://user-images.githubusercontent.com/36522678/92802734-acf7c700-f3ae-11ea-9921-4c0175c23fc8.png)

    But, at the sutta level, only home is shown:

    ![1897bf3f99434c349fa5967936c7ddc3](https://user-images.githubusercontent.com/36522678/92802863-c993ff00-f3ae-11ea-9991-e908e68ef937.png)

**Comment by gnlaera** [comment]
I have just tested drilling down from home page through a specific vagga and the issues reported above persist: when I reached a sutta from a vagga level the breadcrumbs disappear

**Comment by sujato** [comment]
Let's keep discussion to Discourse, otherwise these Github threads quickly become overcrowded. We should use Github only for things that are confident statements of bugs or fixes needed that emerge from conversation.
