### ISSUE TITLE
Segment IDs for localization of site data in Bilara

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/suttacentral#1831]
At the moment in non-static pages strings to be localized are given IDs:

For example, for the search page:

```json
{
    "en": {
        "resultsFor": "results for",
        "metaDescriptionText": "Early Buddhist texts and modern translations. ...",
        "searchResultsText": "Search results for",
        "Search": "Search"
    }
}
```

```html
<span class="search-result-description">${this.localize('resultsFor')}</span>
```

These IDs are usable for Bilara, altough ordering won't be respected: this might not be an issue as often the strings do not occur in any particular order on the page.

## Static Pages

Static pages are different: the strings are not given explicit IDs but are instead created from templates, an example template:

```html
            <h1>
              ${_`SuttaCentral 2018`}
            </h1>
            <p>
              ${_`Welcome to the next generation of SuttaCentral! Our site has gone through a lot of changes since our humble beginnings in 2005. Here’s what’s new.`}
            </p>
            <p>
              ${_`The new site features a new translation of the four Pali <i>nikāyas</i>, ...`}
            </p>
```

That file gets "compiled" into markup like this:

```
            <h1>
              ${this.localize('4e1776b6d0f3ec62485bd2f61ea7f101')}
            </h1>
            <p>
              ${this.localize('d04a1161f90ab33fc1f301fa1fe2f85c')}
            </p>
            <p>
              ${unsafeHTML(this.localize('94cae36a49869be9cc7bb9cdd92ba73b'))}
            </p>
```

And the localization file looks like this:

```json
        "4e1776b6d0f3ec62485bd2f61ea7f101": "SuttaCentral 2018",
        "d04a1161f90ab33fc1f301fa1fe2f85c": "Welcome to the next generation of SuttaCentral! Our site has gone through a lot of changes since our humble beginnings in 2005. Here’s what’s new.",
        "94cae36a49869be9cc7bb9cdd92ba73b": "The new site features a new translation of the four Pali <i>nikāyas</i>, ...",
  ```

Since the strings do not have proper IDs, this is very problematic for Bilara which relies on IDs to know how to order strings, and in this case order can matter as this is a translation of a document rather than discrete UI strings.

## The ugly way

The fasted way to generate strings would be to take the localization files and simply prefix the ID with a number, such as:

```
"1.4e1776b6d0f3ec62485bd2f61ea7f101": "SuttaCentral 2018",
        "2.d04a1161f90ab33fc1f301fa1fe2f85c": "Welcome to the next generation of SuttaCentral! Our site has gone through a lot of changes since our humble beginnings in 2005. Here’s what’s new.",
        "3.94cae36a49869be9cc7bb9cdd92ba73b": "The new site features a new translation of the four Pali <i>nikāyas</i>, ...",
  ```

This will correctly sort in Bilara. It also requires the least modification of the Suttacentral code.

## The clean way

Probably the smartest way to resolve the issue would be to explicitly give strings IDs in the template, perhaps for example in the template page using a structure like this:

```html
            <h1>
              ${_`1.1,SuttaCentral 2018`}
            </h1>
            <p>
              ${_`2.1,Welcome to the next generation of SuttaCentral! Our site has gone through a lot of changes since our humble beginnings in 2005. Here’s what’s new.`}
            </p>
            <p>
              ${_`2.2,The new site features a new translation of the four Pali <i>nikāyas</i>, ...`}
            </p>
```

So in this case, it would be defined that the string always starts with a dotted number and comma, in the compilation phase instead of generating a Hash for the string, it instead strips out the prefix number and uses it as the ID. There would be many possible ways of defining the segment ID.

Note that one reason to use the Hash approach is it makes it clear when the string has actually changed and needs to be re-translated.

**Comment by sujato** [comment]
I'm thinking also of an easy way this can be handled via bilara i/o. Now, if we take the existing sutta texts as the basic paradigm, we have essentially this:

```
   "foo:1:" "string"
   "foo:2": "string" 
```

Why not do the same thing? The ID would be the file title, just as with the suttas. So we might have:

```
  "abbreviations-page:1": "string",
  "abbreviations-page:2": "string",
```

And so on. The number is just a simple increment. Since there is no external reference, there's no need to maintain consistency if they change. 


```
            <p>
              ${this.localize('abbreviations-page:1')}
            </p>
            <p>
              ${unsafeHTML(this.localize('abbreviations-page:2'))}
            </p>
```

That gives us a number of advantages:

- You can see what string it is in a search, it's not dependent on file name.
- The sequence is built-in.
- It's as close as possible to what is already there in Bilara.
- It's obvious looking at it exactly what it is: `abbreviations-page:1` is the first segment in `abbreviations-page`.
- You can edit it easily using bilara i/o. If you add or subtract strings, just re-increment all the IDs. Hashing is not possible in this way, you'd have to use other tools, which is bad. The beauty of Bilara i/o is that you can just use a spreadsheet.

As for the point about changing the hash to indicate needing retranslation, this should not be an issue, as it is in principle no different to the Suttas. We should rely on Git to do this for us. At some point, we can set up a system to notify translators if their source changes. But this applies across the board, not just to UI.

**Comment by thesunshade** [comment]
It appears that this has been resolved, so I'm going to close it.
