### ISSUE TITLE
Rewrite offline page in LitElement, remove Polymer

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1901]
The Offline page is I think the last page needing to be rewritten in LitElement. Take the chance to remove all Polymer.

Keep the functionality the same. Don't worry about stylistic details, just load the static page styles.

**Comment by Prograd** [comment]
Does we really need language selection within offline page? We currently have it in more menu. Therefore we need to adapt sc-language-base-menu to this page. It's not a lot of work. However we can avoid it. On the other hand I'm not sure how it should look like. It can be a selectbox but we can make it a dropdown triggered on button as well.

**Comment by sujato** [comment]
You're probably right. Let's simplify things, remove the language selection from the Offline page. Instead we can just have a bit of text telling people they can change the language from the main menu. (I'll write the text.)

**Comment by Prograd** [comment]
I know this issue is about rewriting page in LitElement. However https://staging.suttacentral.net/api/pwa/collection/sutta?languages=en&root_lang=true this request still doesn't work properly. It's not a blocker for me right now but I think it should be fixed. As a result of this request many other connected with downloading suttas fails. 
![Screenshot from 2021-02-02 13-02-42](https://user-images.githubusercontent.com/26777458/106598094-93227080-6557-11eb-9d20-7f8da759b9ea.png)

**Comment by sujato** [comment]
Can you make a new issue for this? Thanks.

**Comment by Prograd** [comment]
Sure, I will
