### ISSUE TITLE
delete old collections from DB

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1925]
We have transitioned away from the PO data, we need to make sure unused collections are removed from DB.

Running the latest version, following the PO removal, and deleting and rebuilding DB, I see the following collections that should be removed.

most of them are already empty of data.

- [ ] available_languages: empty
- [ ] divisions: empty
- [ ] function_hashes: ? Not sure about this,  don't know what it is **leave for now**
- [ ] grouping: empty
- [ ] pitaka: empty
- [ ] po_markup: empty
- [ ] po_strings: empty
- [ ] root: empty
- [ ] root_edges: empty
- [ ] root_names: empty
- [ ] sect: empty
- [ ] segmented_data: replaced by sc_bilara_data
- [ ] text_divisions: empty

**Comment by alexander-vo** [comment]
`function_hashes` is used by the ChangeTracker tool. This tool is designed as a "watchdog" for data changes (functions, modules, files, etc.) in the application. It's used mostly by load-data and if it sees that some data (files or functions) have not been updated, load-data will not update that data in the database, because it implies that it's up to date.
I don't know if it's needed and I'm not sure I know all the places where it's used, but it's there
I think @blake-sc can give you more details about it.

**Comment by alexander-vo** [comment]
@sujato and what should I do with `available_languages`? The collection is empty and not used anywhere

**Comment by sujato** [comment]
Sure, delete it, I have added it to the list above.
