### ISSUE TITLE
Redesign routing to improve performance

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1949]
Optimize the routing config to reduce resources on Home page and size of JS bundles.

**Comment by robertmusil** [comment]
The optimization process:
- Removing polymer elements that were responsible for routing
- Adding a more verbose configuration for each url 
- Forcing all pages to be lazy loaded, only to load when invoked

**Comment by sujato** [comment]
> Removing polymer elements that were responsible for routing

They'll be replaced with what? 

> Adding a more verbose configuration for each url

I don't really understand this, can you explain it a little for me?

>Forcing all pages to be lazy loaded, only to load when invoked

Okay. Which pages will this affect? I believe the static pages are currently all loaded up front, right?

**Comment by robertmusil** [comment]
1. Replaced by super simple, but also super popular libraries, `path-to-regex` and `history` 
2. basically all the URLS in the application will look like this
```
{
   path: '/donate',
   content: html`<sc-donate></sc-donate>`,
   menu: html`<sc-static-page-menu></sc-static-page-menu>`,
   loader: () => import('./components/sc-donate.js')   // Not real paths, wrting this from different pc 
}
```
There will be some more configuration options here in this dict, because of layout settings, but basically this will be a single place that configures every single page in SC, so its much easier to manage them. Currently to add a page you need to modify several places in the code, its easy to make a mistakes there and there are two different page loaders (static and non-static).
3. All of them. No, static pages are loaded on request currently already
