### ISSUE TITLE
Speed up Github actions

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2065]
We're now using Github Actions extensively, and the performance is an issue. For example, if I want to publish a bunch of text, I have to wait maybe three minutes for each run. Let's consider if there are ways to speed them up. Not knowing anything about it, these are just some wild speculations!

1. **Limit the scope**: currently actions run against the whole repo. Is it possible to only touch the changed files?
2. **Streamline setup**: Currently actions download and install a whole python environment each time. This seems wasteful!
3. **Optimize code**: Perhaps a refactoring could help.
4. **Use golang**: Go is intended for cases such as this, and it often runs 50X faster than python. Of course it means our wonderful programmers have to learn go, so there's that!

This article by a Google Cloud engineer and beta tester for GitHub Actions outlines a number of methods, but the cool one is the last: run a pre-compiled static go binary, resulting in a docker container image <1MB that runs almost instantly.

https://www.sethvargo.com/writing-github-actions-in-go/

**Comment by blake-sc** [comment]
Since the github actions gives detailed profiling information it should be pretty straightforward.

For example in the case of 3 minute publish action, first checking out the two repositories takes 1 minute... that could probably be made quicker with a shallow checkout (no history). The niklhana transformation also takes about 1 minute, the remaining minute is a bunch of misc and sundry stuff.

So yeah, the obvious wins would be to avoid checking out the entire repos (maybe using Github API to just get and add the relevant changed files) and avoid transforming every file.

A more minor win would perhaps be using a docker image more directly ready to run the code, such as a python 3.9 image, that might eliminate some setup time.
