### ISSUE TITLE
"editions" config for publications

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2074]
- A publication is defined in `_publication-v2.json`. 
- Each publication may be expressed as multiple "editions". 
- Each edition pulls in a set of "matter" that describes or informs the publication.
- Editions will normally be different formats (web, epub, pdf, etc.) or else substantial revisions.

The organization of a publication will differ according to the medium. For example, in an EPUB one may want to include a whole nikaya in one file. In a printed book, one may want to split it into several volumes. Again, the requirements for web or for audio may be different.

To cater for these different scenarios, we create a folder for each publication. (eg. `bilara-data/_publications/en/sujato/an/editions`). Inside this folder there are one or more `.json` files that define an edition.

- every published text must have at least one `edition` file, namely the `website` publication.

## naming convention

Such JSON files are named in the following way.

- `uid-language-author_scpub-edition-format_date`

Eg.:

- `mn-en-sujato_scpub3-ed2-epub_2021-04-24.json`

Date uses the standard HTML format ISO 8601.

https://en.wikipedia.org/wiki/ISO_8601

## JSON edition format

The JSON should completely define the content and structure of the output. It would include both:

- direct links to files (for things unique to this publication)
- functions that extract the relevant information from `_publication.json`, the text files, etc.

Here is an example. This defines a book of MN, with a cover image, table of contents, etc. It is divided into 3 volumes, each of which is a separate PDF file, printed as a physical book.

- gather the matter as defined here
- assemble it into a standalone HTML file (or rather, three files for the three volumes)
- convert the files to LaTeX
- create PDF with LuaLaTeX
- upload PDF to print-on-demand service such as Lulu.com (manual task)

`mn-en-sujato_scpub3-ed2-paperback_2021-04-24.json`

```
{
  "publication_number": "scpub3",
  "text_uid": "mn",
  "edition_number": "2",
  "isbn": "abcdefg",
  "cip": "wxyz",
  "publication_type": "paperback",
  "format": "tex",
  "creator": "lualatex",
  "output": "pdf",
  "page_size": "6in, 9in",
  "cover_image": "/matter/img/paperback_cover.jpg",
  "main_toc_depth": "all",
  "secondary_toc": false,
  "number_of_volumes": 3,
  "volumes": [
    {
      "frontmatter": [
        "titlepage",
        "copyright",
        "toc",
        "/matter/foreword.html",
        "/matter/introduction.html",
        "/matter/acknowledgements.html"
      ],
      "mainmatter": [
        "mn-mulapannasa"
      ],
      "endmatter": [
        "index",
        "notes",
        "creator_bio"
      ]
    },
    {
      "frontmatter": [
        "titlepage",
        "copyright",
        "toc"
      ],
      "mainmatter": [
        "mn-majjhimapannasa"
      ],
      "endmatter": [
        "index",
        "notes",
        "creator_bio"
      ]
    },
    {
      "frontmatter": [
        "titlepage",
        "copyright",
        "toc"
      ],
      "mainmatter": [
        "mn-uparipannasa"
      ],
      "endmatter": [
        "index",
        "notes",
        "creator_bio"
      ]
    }
  ]
}
```

***

- [ ] create config for standalone HTML
- [ ] create config for web
- [ ] create config for epub
- [ ] create config for PDF/print

**Comment by thesunshade** [comment]
So happy to hear this is getting underway!

re: epubs
> * generally, keep styles to a minimum, let users define.

As I may have mentioned before, this is a good practice in general, but the specifics matter. In my experience, through the device/software epub(and other related formats) users can control

* the overall zoom level
* the line spacing
* margins (left and right?)
* colour scheme (dark mode, sepia, etc)
* the font (from a limited set)

But other things are not changeable without remaking the book. 

So this is my advice:

***Don't use colour to indicate anything.*** Expect users to be using e-ink where it's only grayscale. Especially don't use any "off black" for any reason as it just decreases the contrast unless the goal really is to make something less readable, e.g. verse numbers.

***Work in em measurements.*** This is good practice generally. The main body text should be 1em

***Do style headings to an appropriate size.*** Devices/software generally have terrible default heading sizes. These should definitely not be left up to the device to decide. It's  possible that h1 may be by default twice the body font size, ending up with a title that fills the entire screen. Just like you would never expect a browser to decide heading sizes, you shouldn't expect an ebook reader to do that either. I find that h1 often works well at 1.4em. It can get tricky if there are more than 3 heading levels.

***Set headings in regular weight*** By default headings will be bolded. In practice this almost always looks bad, and is also unnecessary if the font size is large. The only time I will have bold headings is if a heading font-size has to get down to the same size as paragraph text. 

***Don't use small text for "body" type text.*** Not sure why you would be doing this, but it's a bad practice. You see it sometimes for introductory text. The user has set a zoom size for comfortable reading so the font size shouldn't be messed with. That being said, numbers like verse numbers, paragraph numbers look much better at about .8em of the paragraph size. They are still readable but this helps them to "recede" into the background.

Regarding the font, if you can slim down the embedded font so it only includes the letters that might ever be used in the texts, that's nice for the user and reduces overall file size.

**Comment by sujato** [comment]
Hey thanks, these are all really good suggestions. A minimal CSS sheet can include all these.

Nested headings are a bit of a hassle, we go all the way to `<h6>` in a few cases. Still, it's only really meaningful to style for about three levels.

As for fonts, my research in the past has shown that a) support for embedded fonts is very flaky; and b) most devices include fonts with sufficient character support; specifically Literata (google), Bookerly (amazon), and New York (apple). 

So I'm tending to not include fonts. What do you think?

**Comment by thesunshade** [comment]
> So I'm tending to not include fonts. What do you think?

Yes, that was going to be my suggestion, but then I realized I couldn't back it up beyond my direct experience with Kindles. I'm guessing that android apps would follow any fallback instructions on the fonts, if not just outright fill in missing letters. Personally I'd be inclined to leave them out and then see if anyone complained.

That said, years ago I recall that maybe not all characters were supported for device interface things, so for example if a book title contained a ṁ then it would show a block. But it was so long ago I can't remember the device. A Sony Reader? I'd not worry about that.

I have only minimal experience on variable fonts and I wouldn't expect them to work well across devices. I've never cared about ligatures, although that may have nothing to do with variable fonts. Basically, I'd stick to only the bare minimum.

And yes, the Vinaya texts seem to go to 6 levels if I recall correctly. I think I might have changed the last 2 or three to divs and used bold and italics instead of sizes.

**Comment by sujato** [comment]
For heading levels, maybe something like:

- h1: centered normal 1.5em
- h2: left normal 1.333em
- h3: left normal 1.25em
- h4: left bold 1em
- h5: left italic 1em
- h6 left normal 1em

Margins are probably well-supported, right? So:

 h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 1em 0 0 0;
  }

and 

 h1,
  h2,
  h3 {
    line-height: 1.3333
  }

**Comment by thesunshade** [comment]
I've never worked much with line-height in epubs that I can recall. I think I just let that work itself out.

As I think about the actual heading structure of the book my head starts to spin a little and I'm suddenly not envying the person who has to decide on these things. What you should know, and understandably be frustrated by, is that the Kindle only recognizes two levels of headings in what I call the semantic or device interface table of contents. (A page of html links called a table of contents can be anything you want) That means that, with the MN, for example, If you make `Mūlapaṇṇāsapāḷi` be `h1` and `Mūlapariyāyavagga` be `h2`, you've used up your levels in the table of contents. To work around this I have made both of them be `h1` and then the suttas themselves are `h2`. Crazy, eh? But for the reader it's not really noticeable. For example, this is a shot from the table of contents in Sigil, but it looks very similar to what it does on the Kindle:
![image](https://user-images.githubusercontent.com/82448383/149648087-8c801837-d18c-4dea-af48-c6d4ce354aab.png)
So it ends up looking like there are three levels because the first level starts with the word "Part One..." and the next with an actual number.

I can sympathize with not wanting to accommodate the Kindle, but when it comes to what people are using as far as e-ink devices, that's where it's at. This is basically why I've been creating the special Kindle versions on readingfaithfully.org, to improve the user experience.

**Comment by sujato** [comment]
That's a handy tip, I'll bear it in mind.

See the detailed discussion of heading levels here:

https://github.com/suttacentral/suttacentral/issues/2363

**Comment by blake-sc** [comment]
So I'm going to suggest that all file data sources are specified in the following way:

Say we want to use sujato's translations, that means we want files like:
```
dn1_translation-en-sujato.json
dn1_comment-en-sujato.json
dn1_html.json
dn1_reference.json
(repeat for dn2, dn3, etc)
```

We should fully and exactly specify which file suffixes are being used in the edition:
```
"main_text": "translation-en-sujato",
"notes": "comment-en-sujato",
"markup": "html",
"reference": "reference",
```

These suffixes should be given to the ebook_data_api to inform it what file data to return.

I'm not sure whether this should be specified in the publication or edition files.
