### ISSUE TITLE
QR codes for quick sharing of page links?

### ISSUE THREAD

**Issue by mxmilkiib** [suttacentral/suttacentral#2234]
#### User story
User wants to quickly share sutta address with some people in the room.
User goes to Info tab or new QR Code tab to display a QR code that encodes the page url.
Other users point their phone camera at the image.
The camera app autoscans the QR code, user chooses to open link in browser    

<img src="https://user-images.githubusercontent.com/108225/127756596-a3a13f86-751e-49c6-bf2e-615e2fc33d1c.png" width="250" height="250">

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by sujato** [comment]
Hey thanks for the suggestion!

I really never use QR codes, so consider me ignorant, but may I ask, what kinds of circumstances would you imagine this being used in? 

A sutta class? A casual discussion? social media? university?

And would you know any comparable implementations we might look at?

**Comment by mxmilkiib** [comment]
It would reduce accessibility friction, so in a situation where, maybe due to disability, it's hard for someone to manually copy/enter an address.

Any situation where a link cannot be shared electronically (so generally not so much social media).

University and forms of a sutta class, yes, the person leading could show the code for audience members to scan so they can follow the text in their own way. Or just during a casual discussion, yes.

Most modern phone camera apps automatically scan for qr codes these days. If you have access to a newer mobile, try pointing the camera app at the qr code above, if you haven't already.

There are python modules to generate qr codes, like https://pypi.org/project/qrcode

**Comment by mxmilkiib** [comment]
Given any url can be encoded, there is also the possibility for codes that deep link to specific lines or sections.

There are also the client-side libs like https://davidshimjs.github.io/qrcodejs

**Comment by sujato** [comment]
Okay, good thanks, that's helpful. The accessibility angle is not one I had thought of but yes, it's important.

I'll have a think and put together a spec for such a feature.

**Comment by thesunshade** [comment]
I made a mockup…

Adding it to the share interface:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/f59e089f-6046-442c-88f3-17b0ead80fc2)

And the popup that contains the code:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/c99117a8-2879-402f-ac3d-8f6cae2ba05b)

**Comment by mxmilkiib** [comment]
Nice mockup!

UX wise there's two clicks, which is *somewhat* of a barrier, but if people really want it or it's not felt needed that directly..

The other thing to mention is that; given QR codes are most generally just text, in this context a web address, they could be used to deep link to/access a paragraph directly, not just a sutta.

There is the UI pattern where, when the mouse moves over a paragraph title (or sometimes the whole paragraph), a faint url link chain icon appears at the edge for that paragraph, like with Docutils ([example](https://manual.mixxx.org/2.5/en_gb/chapters/introduction)).

Possibly that could be used to show a way, not with just a deep link chain icon to that paragraph but with two small icons instead, or there be a menu appear, though that again increases the effort, eschewing possibility re visibility/first-class iconographic comprehension by users.

**Comment by thesunshade** [comment]
My thinking was that the number of people using this feature is going to be relatively small, regardless of how important it is for those who do end up using it. Since we already have a "share" UI integrated into the site, I thought it made sense to put it there.

But I'm just a volunteer that likes to make mockups, lol!

As far as the deep linking, I imagine (but of course don't know) that only a small fraction of people who need a QR code would need to the deep links. Most regular users don't even know how to get deep links in the current UI (which may itself be an issue)

Using a mouse to hover to interact with UI elements is inherently unaccessible, not just for screen reader users, etc., but also for mobile. Since Bhante tries to have a mobile first approach, I don't see the feature being implemented that way.

Another thing to consider with the whole issue is that now Chrome (desktop at least) has a built in QR code generator:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/70dd50aa-002c-4fc2-a400-db1127d37b57)

So now that I found that, I'm a little less enthusiastic about building this feature into SC. But again, I'm just a volunteer.

Thanks for your ideas and feedback!

**Comment by thesunshade** [comment]
Ok, I've played around some more and if the user clicks on the segment number of a sutta, then the segment number gets added to the url. e.g. https://suttacentral.net/dn1/en/sujato?lang=en&layout=plain&reference=main&notes=asterisk&highlight=false&script=latin#1.28.1

If you then go to the share in Chrome and Create QR Code, the generated code will link directly to that segment. So it seems that this is already a browser feature that can get you exactly what you are looking for. 

Do you agree, @mxmilkiib?

I have tested this on an adroid phone and both Chrome and Firefox offer generating a QR code, although I suspect that this has more to do with the OS than the browser. As for Firefox, it looks like the feature [has been requested](https://connect.mozilla.org/t5/ideas/include-a-qr-code-generator/idi-p/1719) and is popular but not yet implemented.

Microsoft edge also has the feature. It is accessed by right clicking a blank area of the page:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/38014b7b-a5a7-4f69-a29b-f880181e9ef8)


Generally Bhante Sujato doesn't like to add features to the site that are available in the browser.

**Comment by thesunshade** [comment]
OK, I'm continuing to play around with this.

In FireFox, if you are looking at a page, you can type `qr` at the beginning of of the url, you will get a list of search engines:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/cbc68ea5-4b50-4972-b5b2-7d30f900481f)

If you click on DuckDuckGo, it runs this "search" through their page:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/3ff69043-bd60-4707-925f-23c16b710cf6)

Of course this is no where near as slick as right clicking or choosing from a menu. But it easily creates a QR Code in FF without the need to install any plugins. And of course if someone is willing to install a plugin, there are lots of options.

So at this point there seems to be either built in or almost built in browser features that gives QR Codes for even deep links to the site. 

If I don't hear back from anyone about this I may close this for now, but it could be reopened at any time.

**Comment by mxmilkiib** [comment]
But, like, pretty much no users are going to know that. I didn't know that!

I believe there's a balance that can be struck between annoyingly obtrusive and completely hidden, that's the point of UX design.

I'm not sure why you're thinking about giving up though.

If you think it's hard to implement, then I will likely have a crack at adding it with a user script in Tampermonkey. Everything can be generated client side. Then it wouldn't be hard to add that from the server side.

**Comment by mxmilkiib** [comment]
Oops, sorry, I used a different GitHub client than normal and missed the prior two messages.

I don't think the clicking on a section to add the identifier to the URL, then copying it with a browser feature is sensible. That's not as UI pattern I've ever heard of, and it's essentially hidden from the user.

If sticking hard to browser features, there's no point in a "Copy link" feature.

On the actual use of QR codes, certain sectors of society use them as a matter of course in stone contracts. They've not gone away in the age they've been a thing, so it's helping some people for sure.

**Comment by thesunshade** [comment]
If you are going to work on it then I certainly won't close. 

My point was just that since most users are going to be on a browser that has this feature built in, and since there are lots of browser plugin and even non plugins solutions found at the top of a basic google search for those browsers that don't, that it wasn't necessary.

As I said, I'm just a volunteer. It's really up to Bhante to decide what gets added.

I'm guessing the copy link feature was done because it just takes a line of code and no libraries.

I'd keep in mind though, that the solution should work on mobile by design.

And as I said, I don't doubt that this feature will be useful for those that need it, I just don't feel like it's worth adding to the site since there are many alternatives and the cases for it's use are so narrow.

It's not impossible to set up a local development version of the site, so if your goal is to have it put into the site you might want to give that a try. I just did it using WSL2.

I appreciate your interest!

**Comment by mxmilkiib** [comment]
> My point was just that since most users are going to be on a browser that has this feature built in, and since there are lots of browser plugin and even non plugins solutions found at the top of a basic google search for those browsers that don't, that it wasn't necessary.

As I said, there a high likelyhood a very high number of users don't know about these features. I didn't. You didn't until you researched just now. But having the option "pushed" to the user, rather than "pulled" by the user who is actively looking to learn about possible browser support for generating QR codes, is a different thing, and very much more likely to be noticed and considered as a possibility, so I don't think the statement you made rings true.

But I'll have a look for sure. I already tried to use OpenAI and Google Gemini (nee Bard) to generate a user script, and they did, but I just got back from a club night a couple of hours ago, and I believe I'm needing to better phrase the prompt to work with the dynamically generated JS pages of SC.

**Comment by thesunshade** [comment]
I guess I was assuming from your user story that someone presenting like that would already have experience enough to know what a qr code is and that it is a useful way to share a link with people in a room. From that I gathered that they would be doing a google search to figure out how to do it. Someone who had no idea about qr code sharing would not know by looking at a menu option (either in the browser or in the website itself as a feature) that this would be a solution to their problem. 

All that aside, I tried to think about how *I* might use a feature like this (because I'm currently imagining there aren't that many uses). Low and behold I came up with one I could use this weekend! I have a sutta class where I give a handout with the English sutta translation. In the past I have just included the link to the sutta. But now I have added a QR code. 

So for my use case I can easily use the browser feature. But I'm on FF, so I have to switch to Chrome. No big deal. (assuming I forgot about putting `qr` at the start of the url bar and clicking DuckDuck, which is really the best way to do it in FF) No big deal. In Chrome I right click on the page (as I do in Edge) and get this:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/474e4055-be4a-4ee8-b0a1-78a3c7bb53a3)

I select the Create QR code for this page. Then I get this:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/c9fb8ccb-b506-4e3f-a2bd-6cafd993cc49)

Now what I really love for my use case is the copy and download buttons. Because that's exactly what I need to do. I need to copy the code and paste it into my handout document. Great!

What I definitely *don't* like is the Mozilla branding in the middle of the code. 😤

Edge has an almost identical output, but there is no branding:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/9cbd8f95-2bbe-4efb-9ae2-0de49d349efe)

I'm not exactly sure why they both have an input box with the page link, but I like it.

I don't know what features the library you were thinking about using, but it would be awesome if the code could include SuttaCentral branding:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/ad247fc7-3515-476a-b34e-dd7a26f86639)

**Comment by thesunshade** [comment]
I have created a [thread on this topic on the forum](https://discourse.suttacentral.net/t/how-would-you-use-a-qr-code-feature-on-suttacentral/32685) to get more feedback.

**Comment by ihongda** [comment]
![image](https://github.com/user-attachments/assets/65e0d5b6-b66d-45bf-9524-faea7b786f79)

I made a prototype of the sharing menu in the suttaplex card

**Comment by thesunshade** [comment]
I'd suggest talking directly with Bhante Sujato about this before implementing.

If it does happen, a common aspect of these qr-code generators is a click-to-copy feature that allows people to share it. Simply putting it up on the screen would let someone point their phone at the computer screen to get the url, but it won't help if people want to share it. At least not easily.

**Comment by mxmilkiib** [comment]
Thanks @thesunshade for creating an implemention for a page QR code!

Could still though the idea of a QR code for each line somehow be factored in? This would enable deep linking.

Every sentence has a unique id for their spans (sādhu!) that serves as an anchor. Some kind of subtle mouseover UI element? Maybe over or clicking/tapping the line number. And maybe also for the UI format could also be shared?

https://suttacentral.net/dn1/en/sujato#dn1:1.4.2

https://suttacentral.net/dn1/en/sujato?lang=en&layout=sidebyside&reference=main&notes=sidenotes&highlight=true&script=latin#dn1:1.4.2

etc.

Quick transfer of specific locations in the texts is the feature, maybe individual users seeking to get a reference from a PC to their phone might be the biggest use case.

A QR can also be projected, so for talks to quickly pass on a reference or section for later personal analysis and/or meditation.

Could also be fly posted, used in art, etc. etc.

**Comment by firepick1** [comment]
Unlike URLs, which are easily inspected to reassure users, QR Codes are prone to [social engineering attacks](https://abnormalsecurity.com/blog/qr-code-phishing-attacks?utm_source=google&utm_medium=Paid%20Search&utm_content=nonbrand-quishing&utm_term=qr%20code%20phishing&gad_source=1&gclid=CjwKCAjw7s20BhBFEiwABVIMreHaxdR3XRllEAjR_--Y3vzi7d5fxeB-oERAmJ6orwJfqeYgR-YJTxoCqeEQAvD_BwE) in phishing. QR Codes can just as easily point to malware sites as well as trustworthy sites. I personally dread taking pictures of QR codes unless they are on a trusted websites.  

I would instead advocate for reliance on the use of the trusty URL. SuttaCentral's URLs are beautifully simple and well designed.  Here is a link to [AN11.7](https://suttacentral.net/an11.7). You'll notice that hovering over the link will reveal a trustworthy familiar website. Such a URL can easily be pasted into an online lecture chat window and easily typed into the browser URL field. Yes, QR Codes are snappy and convenient, but it's so easy lull people nito mistakenly trusting any QR Code they see.

SuttaCentral also allows users to share segment linkes such as  [AN11.7 segment 2.2](https://suttacentral.net/an11.17/en/sujato?lang=en&layout=sidebyside&reference=main%2Cms&notes=none&highlight=false&script=latin#2.2). These URLs are more complex.

For accessibility, I'd recommend [sc-voice.net,](https://sc-voice.net) which will speak the suttas. SC-Voice.net URLs have simpler segment links. SC-Voice also has the ability to copy the Markdown version of a verse along with its link. The SC-Voice "copy quote" ability is very useful for posting on social forums.

**Comment by mxmilkiib** [comment]
I don't understand your concern regarding QR codes in relation to SuttaCentral

Society has gotten a lot more wise to phishing, and "words" are used in such attacks, should we stop using those? But words can be used to help educate, and so can QR codes

QR codes contain text, phones display the text on scanning, the user has the option to open the link if it's a link

Scanning a QR code would show the beautiful URL you mention to the user

And SC is a "trusted website"

I know some camera apps have a site preview facility too. When talking about hovering over, are you talking about Chrome or Safari? I guess your experience is different

I don't think the worry that using QR codes will encourage people to get less savvy in their digital literacy skills makes sense

Would it be too much for me to request some sublime holdings for the side of society that doesn't have problems with using new communications technology and not getting scammed

SC could even intentionally signpost users to information on such to edumacate to help

But there's oceans of worth in using them now, the tide can't be turned; https://google.com/search?q=digital+literacy+education+qr+codes

(Mentioning accessibility makes me think of another aside; how early and clearly in the screen reading experience of SC, either from the front or from a deep link to a page, is the Voice site highlighted/signposted. Idk)

**Comment by thesunshade** [comment]
I think the bigger issue is that every new feature added to a site comes at a cost, even if it seems small. And the fact remains that there are many alternatives either built into the browser or through third party sites. 

Also, when considering the burden of new features, you have to consider how many people will use the feature. And I just can't see the need. Especially when people who do frequently use qr codes must already be using third party solutions.

I'm not saying no one would use this. I just don't think that there is any unique benefit over using third party solutions.

In any case I thin Bhante @sujato needs to weigh in before any more developer time gets spent on this. Keep in mind that there are already over 100 issues just on this repository waiting for attention.

**Comment by mxmilkiib** [comment]
Can whatever browser (or extension) quickly display a line anchor specific QR code?

So-called affordance is a factor; making the ability easy to access, sans browser extension (or lack of ability for id anchor links? Idk?), sans having to know your browser, or give up the one you use

Any tiny QR code JS lib/module used, downloaded compressed once (from a CDN) and cached locally perpetually, with any code generation code pathway only being hit on use, would seem to me not that weighty an asset

And it's directly aimed towards the principal of sharing the dhamma

Just a few 2 pences anyhow in case any consideration might depend on making these points! :)

**Comment by firepick1** [comment]
> And SC is a "trusted website"

Quite so. And because of this _a single QR-Code for the site on the front page_ might indeed be useful and appropriate as a beckoning gesture.  I recently went to a restaurant and there was a QR Code on each table. Such uses are wonderful--they simplify the merchant's life as well as the customers. We were going to use it to order, but the smiling waiter was kind enough to help us before we could whip out our phones. It was nice to have the possibility of ordering if the nice waiter was too busy to exchange human pleasantries.

But the other thing I noticed is that the QR Code is a rather prominent feature that demands attention. In fact all great uses of QR Codes that I have seen are, well, exclamatory (TRY THIS NOW!!) and transactional with an accompanying sales pitch.  In other words, their purpose is to grab, channel and direct attention.  This is quite in stark contrast with the unobtrusive humble links we see on Wikipedia pages.  In our journey on the Noble Eightfold Path, our practice involves guarding the sense gates. Unlike the humble link that offers possibility without insisting, the QR Code by its very square boldness presents an imperious battering ram of demand on the senses with a loud call to action. It's a gaudy call to attention. Contrast that with the rather gentle 🔗 symbol that offers the kind possibility of a clipboard reference.  The following quote with link was generated with a single click from SC-Voice:

> [sn35.132:5.1](https://www.sc-voice.net/#/sutta/sn35.132:5.1/en/sujato) <i>Aguttadvārassa bhavanti moghā, </i>  
> [sn35.132:5.1](https://www.sc-voice.net/#/sutta/sn35.132:5.1/en/sujato) All is vain for someone <j>who doesn’t <span class="scv-matched"><span class="ebt-example">guard the sense doors</span></span>,   

For SuttaCentral, I think the 🔗 symbol appearing on hover near each segment would be far more useful than a QR Code.  The front page and perhaps even the suttaplex cards might have a use for a QR Code. But I also think that we need to understand the sensory impact of the garish QR Code.

BTW, the security concerns of QR Codes are real.  Someone might make a malware QR Code sticker and paste that on a major chain's physical menus  with a URL that takes them to a phishing site that acts as trojan horse, capturing PII and then redirecting the user to the real web page.  It is VERY easy to fool people.  This example of phishing does not apply to SuttaCentral of course, since it's a website and stickers won't work.  But their very utility lulls us into trusting QR-Codes.

**Comment by sujato** [comment]
Dear friends,

Thanks so much to everyone for their contributions, i've learned a lot about QR codes!

I understand that the implementation would be relatively simple, although still not nothing. I also understand that some people like the idea, some not.

One of my basic rules for web design is this:

>Thou shalt not implement in thy web app functionality that is already present in thy browser.

The basic functionality of supplying a QR code for a web page is indeed available in most browsers, and it seem to me this will readily cater for most use cases. Over the years, I have not seen demand from readers for anything more.

@mxmilkiib you mentioned about the ability to create deep links from segment IDs as an additional feature. But I just tested this, and Chrome already does this. Click on a link to a segment, it creates a URL with a number at the end (eg. #123), right click, QR code it; point a phone at the QR code and go to the link, there it is. This could easily be used in classes. 

So with thanks, I am going to say no to this feature, and close the issue.

**Comment by mxmilkiib** [comment]
Okies! N.b. the contention would be Goggle's [unilateral gun jumping](https://theregister.com/2020/02/20/chrome_deploys_deeplinking/) with a [feature](https://developer.mozilla.org/en-US/docs/Web/Text_fragments) that only their browser engine supports. And I wonder if Chrome does support QR generation of those deep links.

**Comment by firepick1** [comment]
@mxmilkiib I remember once that Internet Explorer started unilateral gun jumping and it bothered me so much I went to Chrome. Years later IE died of overgrown and calcified hubris.  Chrome itself is starting to look like a dystopian former school bus festooned with garish regalia and populated by righteous zealots on epic missions du jour. Given Bhante's post, I eventually noticed the QR menu item myself--but who knows what the G-zealots intend for deep links...

I still have QR code stickers for my garden. But I gave up and just started talking to the plants and asking them how they are doing. :seedling: :sun_with_face:

**Comment by thesunshade** [comment]
@mxmilkiib This feature has now been added through the still-under-construction SC Browser Extension:

https://discourse.suttacentral.net/t/developing-a-browser-plugin-for-suttacentral/36074/50

![image](https://github.com/user-attachments/assets/bc3fb064-34be-44b0-95d1-7aa022cddda8)

It supports "deep linking" simply by clicking on the segment number and then pressing <kbd>q</kbd> to get the code.

Would love it if you could test and try to break 😅

**Comment by agilgur5** [comment]
> Click on a link to a segment, it creates a URL with a number at the end (eg. `#123`)

> N.b. the contention would be Goggle's [unilateral gun jumping](https://theregister.com/2020/02/20/chrome_deploys_deeplinking/) with a [feature](https://developer.mozilla.org/en-US/docs/Web/Text_fragments) that only their browser engine supports. And I wonder if Chrome does support QR generation of those deep links.

Just to clarify, Bhante Sujato was not referring to that Chrome feature, but SC's own segment anchor feature. For example, as in the above screenshot, https://suttacentral.net/an11.11/en/sujato#1.4, the `#1.4` portion at the end is an anchor to the specific segment (see more options under "views" > "References").
That [feature of anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#linking_to_an_element_on_the_same_page) has long existed; since Chrome v1, Firefox v10, Safari v4, etc and is well-supported in all modern browsers (see `href = '#top'` in [MDN's browser compat section](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#browser_compatibility))

**Comment by mxmilkiib** [comment]
thanks for the clarification, you're correct, I quite fubbed my analysis there, can't remember how, possibly brain fog

so;

Firefox doesn't have a feature in the UI to generate QR codes from anchors (which would include #id) yet ([feature request](https://connect.mozilla.org/t5/ideas/include-a-qr-code-generator/idi-p/1719))

it does however, as of last month, have the backend browser engine capability to generate them ([bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1996315))

but there is not yet a general issue to track implementation of the front-end aspect (only for [in File menu on macOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1996321))

maybe the upcoming FF redesign will include a completion of this functionality,
though I suspect not given the lack of activity relating to such in the existing issue
I'll not attempt even a rough guess for when, could be a few months, or several years (general [e.g](https://bugs.kde.org/show_bug.cgi?id=107302)),
though if I were to hope/expect; maybe within 2y
