### ISSUE TITLE
The ATB for the Tipitaka essays is buggy

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2313]
Each of the three main Pitakas has an attached essay, navigable from the Home page card.

https://suttacentral.net/discourses-guide-sujato
https://suttacentral.net/vinaya-guide-brahmali
https://suttacentral.net/abhidhamma-guide-sujato

When you click on any one of these, it should take you to the relevant essay. This works fine.

But when you are on that essay, it should display the *three* essays in the Adaptive Tab Bar (ATB).

![Screenshot from 2021-10-30 08-21-18](https://user-images.githubusercontent.com/6112010/139503185-5bd51a74-a828-4cce-96fc-ed62c83cb6cd.png)

However this does not work reliably, sometimes it has the wrong items in the ATB:

![Screenshot from 2021-10-30 08-23-08](https://user-images.githubusercontent.com/6112010/139503428-53a35ec1-d6cd-42f7-93f7-4f0dab3912bd.png)

-  **When on a Tipitaka essay, the ATB must always display the three Tipitaka essays.**

**Comment by sabbamitta** [comment]
>However this does not work reliably, sometimes it has the wrong items in the ATB:

Not only this. Sometimes, the items look correct, but the attached links are not.
![Screenshot from 2021-10-29 22-54-11](https://user-images.githubusercontent.com/43345786/139524083-085d11a4-115e-45ec-bd30-5859181231a4.png):

When you are in the Sutta essay, the links to Vinaya and Abhidhamma go to a page with suttaplex cards instead of the essays.

When you are in one of the other essays, clicking on the link to the Sutta essay ("Lehrreden") leads into nowhere land ("null" in the tab …):
![Screenshot from 2021-10-30 09-17-47](https://user-images.githubusercontent.com/43345786/139524234-5a3c46b1-ae5c-4693-a3a1-54c833a6e591.png)
