### ISSUE TITLE
re-search: brand new search for SuttaCentral

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2383]
A fundamental problem we face is: "how do we find things?" Suttas are not easy to discover and pose a range of challenges for search.

We have for many years relied on elasticsearch. While this is a robust and powerful application, it is also very resource heavy, and uses a very different paradigm than the rest of the site.

In recent years, ArangoDB has developed very powerful text search features. We believe we can equal or better the functions of elasticsearch, while relying on the familiar software interface we use for the rest of the site. Check it out!

https://www.arangodb.com/docs/stable/arangosearch.html

**Aims:**

- don't lose any current functionality
- fix bugs
- build new features
- make things that are surprising and delightful

## general requirements

- [x] ensure all search results are shareable by URL
- [x] ensure all search results are superfast
- [x] case-insensitive
- [x] diacriticals policy: if search term has diacriticals, match them exactly. If it lacks them, match fuzzily.
    - *bhāva* returns *bhāva*
    - *bhava* returns *bhava* and *bhāva*. 
- [x] prioritize texts with segmented translations (even if searching for root).

## current features

Elasticsearch currently does quite a few things. Let's make sure we don't break any of them.

- [x] full text search in many languages (how many?)
- [x] fast and reliable
- [x] results link to texts
- [x] fuzzy search
- [x] search for words returns dictionary entries
- [x] search for places returns map
- [x] search for sutta UID returns correct sutta
- [x] prioritize exact matches
- [x] see these operators (recently broken by case-insensitive URLs) https://discourse.suttacentral.net/t/searching-suttacentral/10195/13?u=sujato

## current bugs

Let's fix annoyances

- [x] search results don't prioritize exact or close string matches using phrases. I.e. search for "one time" and you'll get results for "one", "time", and "one time". The results should prioritize "one time" and then "one" and "time".
- [x] Root language results should link to segmented translation text where available.
- [x] ensure return sutta UID works with less-popular texts
- [x] match partial words
- [x] The "filter" dropdown is broken. fix or remove or change it.
- [x] prioritize titles (contents of `name` files and things in `sutta-title`)
- [x] make sure references and other cruft does not appear in search results

## new features

- [x] instant search
- [x] vol/page searches
- [ ] alias popular queries
- [x] add search filters (like Github)
- [ ] populate nav pages with contextual search boxes
- [x] move map off google maps 
- [x] add richer context to search results (suttaplex)
- [x] search in static pages
- [x] more search hints
- [ ] "search within" function for large searches.
- [ ] "literal string" matches
- [ ] #3048
- [ ] #3049
- [ ] #3050
- [ ] other? are there any fun features we can implement?

**Comment by thesunshade** [comment]
I'm very happy to see that fuzzy search is on your mind. It would be great if fuzzy could extend to at least aspirated and non aspirated. On a practical level, the h is just as much a diacritic as lines and dots. Unless you were only thinking to include diacritics because they are hard to type. I feel that when it comes to non-experts, aspirates—as well as double consonants for that matter—are just as tricky as real diacritics when it comes to knowing how to spell a word. 

Perhaps it could be an option or a fall back if there are no other results? In the grand scheme of things, I realize this is kind of a luxury. But I do think it could be helpful.

> * alias popular queries

I wonder if by this you are meaning that a search for `karanīyamettā` would actually get you to Khp9. I think on such famous suttas one should be able to get to it by its most famous name.

There should also be more flexibility in entering citations. For example `mn125` will return that sutta, however `mn 125` returns five suttas from MN, none of which are 123.

It also seems wrong that `Dantabhūmisutta` will get you to that sutta but `Dantabhūmi sutta` does not. At all.

**Comment by thesunshade** [comment]
I am going to close this issue for now. Any unfinished tasks either already had their own issues and I created new ones for those that didn't.
