### ISSUE TITLE
bi pc 91-93 is not working properly

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2528]
Bi Pc 91, 92, and 93 are all combined in one file, bi-pc91-93. But they don't appear in the navigation at all, we have separate suttaplexes. There should be just one suttaplex, and it should have the texts for brahmali and the pali. Also, the navigation is not working, this must be tested too.

![Screenshot from 2022-09-28 19-28-11](https://user-images.githubusercontent.com/6112010/192743733-cf6ab03b-5b5e-44d4-a532-7615d0768be4.png)

**Comment by ihongda** [comment]
The reason is that the related `name` and 'tree' json files are missing the `pli-tv-bi-vb-pc91-93"` key and value:

https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/root/misc/site/name/vinaya/pli-tv-bi-vb-name_root-misc-site.json

https://github.com/suttacentral/sc-data/blob/master/structure/tree/vinaya/pli-tv-bi-vb-tree.json

**Comment by sujato** [comment]
Oh right, I think the problem is that I made the changes in sc-data on a branch, and didn't merge to master. I think this should be resolved with the following PR:

https://github.com/suttacentral/sc-data/pull/162/

Can you please check and make sure the merge is correct?

**Comment by ihongda** [comment]
Got it, Bhante, I will check that!

**Comment by ihongda** [comment]
![截图 2022-10-24 16-56-15](https://user-images.githubusercontent.com/4037966/197488143-eb93213c-bedc-432c-a818-262c0a094156.png)


It look like normal!
