### ISSUE TITLE
Add explicit indicator of no modern translation found on SuttaPlex card

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2562]
Currently when there is no translation of a sutta in the user's chosen language, the section on the SuttaPlex card is simply blank

![](https://scdd.sfo2.cdn.digitaloceanspaces.com/uploads/original/3X/d/4/d4052b365238ebfaa214ed2bf965675b869d6ea7.png)

It seems to me like the ideal interface would explicitly indicate that no translation existed. I’m trying to look at things from the perspective of a completely new user.

It looks like there is never a parenthetical counter for the chosen language heading, otherwise at a minimum it could indicate (0) if there were no translations. But an explicit “No translations available” would be better.

**Comment by sujato** [comment]
Indeed, this is a nice UI improvement.

I agree that an explicit "no translations available" would be better, but a simple (0) would do the job, be easier to implement and more robust (because it doesn't require translation). We can, I think, add a translation count easily, *if* that data is already in the API, which it should be (I think!).

Let's do this:

- determine whether translation count is available in the suttaplex API
- If so, add it, including (0) if there are no translations.
- Use the same markup as for numbers in other translations.

If the number is not available in the API, then let's reconsider. The options would be:

- add it to the API
- calculate it on the front end (more javascript, yuk)
- add "no translations" (which would then need to be localized)

**Comment by thesunshade** [comment]
> * add "no translations" (which would then need to be localized)

I totally get wanting to keep the items in the interface localization to a minimum. However, I am guessing that "no translations" is fairly simple English for a non-English speaker to understand as that would be the fallback.

Also, since this message will be showing *mainly* for users who have selected a non-English user interface, it seems like a courtesy to be able to put it in their language. (I guess for non-Pali texts there will be a lot of English users also seeing the message.)

Finally, the phrase "No translations" is very trivial to translate, even out of context, so it's not a big burden on volunteers.

All that said, just having `(0)` would be great.

Thanks for considering this.

**Comment by sujato** [comment]
Let's look at having the number first and see how. (I'm always looking for any way, no matter how trivial, to reduce the burden for programmers and volunteers.)

**Comment by ihongda** [comment]
The current way is that if the number of translations in the language selected by the user is 0, the section will not be displayed at all. @thesunshade

**Comment by thesunshade** [comment]
Thanks for working on this!

There is a slight language/logic problem with this situation:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/cefed0d8-29e8-4f99-81dc-fadc57eb9102)

"Other modern languages" presumes that there is *some* modern language that comes before it.

I don't know if this is worth fixing. Or even how with the current behaviour. 

Personally I'm still in favour of explicitly indicating that there is no translation in the selected user language. Otherwise someone might think they need to look in that list for their own language. But of course they won't find it.

**Comment by ihongda** [comment]
> Personally I'm still in favour of explicitly indicating that there is no translation in the selected user language. Otherwise someone might think they need to look in that list for their own language. But of course they won't find it.

It is indeed possible to cause this kind of misunderstanding, let me try to modify it.
