### ISSUE TITLE
Show subsections in Table of Contents

### ISSUE THREAD

**Issue by vwkd** [suttacentral/suttacentral#2681]
#### User story

It would be helpful to also show subsections in the Table of Contents. Concretely, headers h3 and lower (h4, h5, ...).

Here's a visual example of the Table of Contents of [DN1](https://suttacentral.net/dn1/en/sujato) and a missing subsection.

<img width="609" alt="pic" src="https://github.com/suttacentral/suttacentral/assets/33468089/ef86c666-795f-4eeb-a223-04ab4128615a">

From digging around a bit it looks like the TOC is generated on-the-fly on the client in [client/elements/text/sc-text-bilara.js#L685](https://github.com/suttacentral/suttacentral/blob/fcb18dfa02bfba07f6972f4b8b005502505bd5bb/client/elements/text/sc-text-bilara.js#L685) by querying `h2` elements and then rendered in [client/elements/addons/sc-top-sheet-toc.js#L55-L77](https://github.com/suttacentral/suttacentral/blob/fcb18dfa02bfba07f6972f4b8b005502505bd5bb/client/elements/addons/sc-top-sheet-toc.js#L55-L77). This could be changed to generate the TOC as a tree and then render that tree.

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by ihongda** [comment]
Thanks @vwkd , that's a great suggestion, I'm implementing it 😄

**Comment by sujato** [comment]
Ahh, let's pause this, I'm not sure it is a good idea. 

I implemented ToC on `<h2>` specifically to provide a balance of usability and complexity. There are close to 10,000 instances of subheadings in our Pali texts alone, and we have to ensure we are doing the right thing for all of them. 

A very long and complex ToC conflicts with the UI approach we are currently using, which places the ToC in a top sheet. This works best with a glanceable ToC of half a dozen items or so. Kd 11 for example has 42 `<h3>` tags, while some chapters of the Abhidhamma have 100. Forcing a user to scroll past them all makes the ToC effectively unusable. Limiting ToC to `<h2>` is a simple and efficient way of avoiding this problem.

Some applications (Discourse forum for example) get around this by putting the ToC in the side, then unfolding the levels as you scroll down. Very nice, but is that what we want? What other things we set aside in order to build it? How much complexity are we adding? Is there another UI approach we could use? And so on!  It's a lot of time and effort. Check meta.discourse history, it took *years* for Discourse to build their ToC implementation. 

All these things need to be considered carefully before putting time into something like this.
