### ISSUE TITLE
new static page for sponsoring printing

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2860]
We are collaborating with the Sri Lankan Sangha to print 1,000 sets of translations in English of the Suttas and Vinaya. This is a major project, which will result in SC's texts being available throughout monastic education in Sri Lanka.

To make this happen, we need to raise funds for printing. Let us create a new static page for this.

The page should include a target graphic so we can keep track. We will have a firm fundraising target for printing, so let's make a pie chart or some other graphic to illustrate the progress. We can keep it simple, update the graphic by hand on a weekly basis. 

- [x] create new static page at suttacentral.net/sponsor (hongda)
- [ ] add content to /sponsor (sujato)
- [ ] build form for sponsors to donate (hongda)
- [ ] add progress chart to /sponsor (hongda)
    - make sure chart uses SC's colors!
    - maybe reuse the pie charts on the /languages pages? (https://suttacentral.net/languages/en)
- [ ] add card on Home page (sujato)
- [ ] link to /sponsor from /home and also from /editions (sujato)

Note, we should not deploy this page until the fundraising banner is stopped, we don't want two campaigns at the same time!

**Comment by ihongda** [comment]
Bhante @sujato , I have added the sponsor page:

https://github.com/suttacentral/suttacentral/pull/2863

**Comment by thesunshade** [comment]
When the time comes I am happy to localize this page.

Just as an aside, this is one specific use case where forcing the loading of a specific language page makes sense. I can see how someone would want to share a Sinhala version (or Thai, or whatever really) to target a specific audience. This is because this target audience may not be users who would have set their site language to their local language. And since most Sri Lankans (to my knowledge) don't set their browser language to Sinhala, even automatically setting SC to the browser language wouldn't work.

Currently there is no sharing feature on static pages. Perhaps this could be a use case for implementing one.

**Comment by sujato** [comment]
Thanks to everyone for your contributions to this. Currently this is on hold, as we are in negotiations with the nikayas in Sri Lanka, and they are getting students to read and review the translations before giving the final go ahead. This is good, as it shows due diligence on their part. We should be ready to go ahead rapidly when we get the a-ok from them.

**Comment by thesunshade** [comment]
I'm also happy to help building out the page when you have text to add.

**Comment by thesunshade** [comment]
I believe this is finished.
