### ISSUE TITLE
Last chapter of Pali Dhammapada should not lead you "Next" to the Udānavarga

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2951]
#### Description:

The [last chapter](https://suttacentral.net/dhp383-423/en/sujato?lang=en&layout=sidebyside&reference=main&notes=none&highlight=false&script=latin) of the Dhammapada's "Next" button takes you to the [first chapter](https://suttacentral.net/uv1/en/sujato?lang=en&reference=main&highlight=false) of the Udānavarga. This means you are being taken from one root language (Pali) to another (Sanskrit). The Udānavarga is not part of the Pali Khuddakanikāya.

It appears that the last sutta/chapter in the KN will take you to the first sutta/chapter in the next book. I actually question this behaviour as well since they are for all intents and purposes different books in the same way DN and MN are different books. And the last sutta of DN does not take you to the first sutta of MN (for example).

#### Steps to reproduce:

Go to the last chapter of the Dhammapada: https://suttacentral.net/dhp383-423/en/sujato

Go to the end of the page. Find the "Next" button. Clicking on it takes you to the first chapter of the Udānavarga.

#### Expected behaviour:

There should be no next button in the last chapter of the Pali Dhammapada since it's the end of the book. Or at the very least, "next" should take you to the first chapter of the Udana.

(it looks like the first sutta of Ud has a "previous" button to take you to the last chapter of the Dhp. And the first chapter of Uv does *not* have a "previous" button.

#### Screenshots:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/a8d74b89-5885-42af-834c-753506119d67)

**Comment by mtnadi** [comment]
So, the previous/next is entirely computed out of the navigation menu, (query `ALL_DOC_UID_BY_ROOT_UID`)
It appears since we wanted the various dharmapadas [collected together](http://suttacentral.net/pitaka/sutta/minor/dharmapadas), there ends up being two entries in `super_nav_details_edges` where `_to = super_nav_details/dhp`, one with `_from: super_nav_details/dharmapadas` and one with `_from: super_nav_details/kn`.  The prev/next computery thingy is obviously choosing the record for `dharmapadas` instead of `kn`.

(I haven't understood enough to propose any solutions, but if someone gives me pointers I can attempt to implement and test though.)

**Comment by thesunshade** [comment]
I know even less than you, but it does sound like you have diagnosed the problem.

I believe @ihongda is busy these days working on Bilara, but perhaps he can pop in to advise.

**Comment by ihongda** [comment]
@thesunshade @mtnadi 

I've adjusted the related AQL and looks like can resolve this problem, I'll push it to `Staging` later.
