### ISSUE TITLE
Partial Search can't find ekībhāva

### ISSUE THREAD

**Issue by khemarato** [suttacentral/suttacentral#2959]
#### Description:
Partial matches just look for strict substring matches which doesn't always work well with sandhi/case endings

#### Steps to reproduce:

* search for ekībhāva with partial matching enabled

#### Expected behaviour:

Suttas containing "ekībhāvāya" are returned 

#### Actual behavior

Nothing returned. I have to erase the last -a of my search for it to find -ā.*

**Comment by khemarato** [comment]
One simple fix that would work in this case and perhaps be helpful more broadly would be to simply do an accent-agnostic search automatically if the initial (diacritic-aware) search fails. This would also bring site search up to parity with how instant search works

**Comment by thesunshade** [comment]
I thought both searches were ignoring all diacritics. 

Personally, I feel like "misspelling" is different between root languages and translation languages. While it's true that not including diacritics is a type of misspelling, the more likely reason someone won't include them is because they don't have a way to type them.

In my [sutta title lookup app](https://name.readingfaithfully.org/) I have an extreme "ignore diacritics" option where it also ignores the "h" in aspirated consonants as well as double consonants (it treats single and double consonants as the same thing, so the user can use single and find double or double and find single). I did this because many non-specialists may not remember if a word is spelled with a long vowel or double consonant.

Interestingly, I find that using this setting does not dramatically increase the number of hits.

My preference would be that all ***Pali*** diacritics are always ignored in both searches. This would also solve the m-underdot/overdot issue. But full disclosure: I never use SC for Pali searches.

> do an accent-agnostic search automatically if the initial (diacritic-aware) search fails.

This would also be great.

Diacritics for translation languages should not be ignored, imo.

I wouldn't mind if there were a toggle switch for this.

**Comment by thesunshade** [comment]
Great work!

It looks like on the instant search side everything is perfect:


![Image](https://github.com/suttacentral/suttacentral/assets/82448383/33d0bbb8-0fa0-4ffa-ba8c-e19f2aef1e42)


However on the full database search, we have the highlighted terms with the diacritics stripped:



![Image](https://github.com/suttacentral/suttacentral/assets/82448383/b45ce0f9-e132-4305-941d-eea9e7386881)

Here you can see what the actual text looks like:


![Image](https://github.com/suttacentral/suttacentral/assets/82448383/2c5b5534-f690-48c0-9c0f-63b4e18b8d96)


Good news is that the dictionary search highlight is fine.

**Comment by ihongda** [comment]
>However on the full database search, we have the highlighted terms with the diacritics stripped:

This problem has been resloved.

Will close this issue @buddhist-uni @thesunshade

**Comment by thesunshade** [comment]
I noticed this strange behaviour:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/7cb297dc-e450-4f6f-a31d-80864fc1cbb3)

Just as an FYI. Something we should keep an eye on.

**Comment by khemarato** [comment]
The off-by-one error in the highlight? Seems like an unrelated bug that should get its own Issue
