### ISSUE TITLE
Add "notification" that there are more translations of a text in user's language

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2989]
#### User story

John is new to the site. He is sent a link to a sutta. Looking at that sutta there is no indication at all that there might be another translation of the *exact same sutta* because it's behind a couple of clicks. Poor John.

Elizabeth is very familiar with the site, however every time she wants to know if there is an additional translation of the text she is reading, she must click on the Parallels icon to see. She may even forget to check since it's not clear what might be waiting for her. 

#### Feature description

If there is more than one translation of a text into the user's chosen site language, show some kind of indicator on the Parallels icon.
<img src="https://github.com/suttacentral/suttacentral/assets/82448383/3aa214c5-b517-4944-8368-a7b3d911193a" width=400>

<img src="https://github.com/suttacentral/suttacentral/assets/82448383/143638ae-f54e-4ed0-8a07-566e0207d89d" width=400>

#### Pre milestone planning check:
- [ ] Small enough to completed in a milestone.
- [ ] Dependencies marked
- [ ] No external dependencies block the PBI from being completed.
- [ ] Details are understood by dev team to decide if the PBI can be completed.

#### Done check:
- [ ] Produced code for presumed functionalities
- [ ] Project builds without errors
- [ ] Peer Code Review performed/pull request approved x2
- [ ] Project deployed on the stage environment identical to production platform
- [ ] Feature is tested against acceptance criteria
- [ ] Feature ok-ed by Product Owner (moving to Closed on the Board)
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented (readme, etc...)

**Comment by khemarato** [comment]
Nice! Would save me a click sometimes. I just hope this feature doesn't come with a performance cost. The site already takes a long time to load a sutta 😅

**Comment by thesunshade** [comment]
I think the api used to render the page already has the data on other translations, but I'm not sure. There does seem to be an additional api call when the parallels icon is clicked, so maybe not. But those API calls are lightening fast in my experience.

**Comment by khemarato** [comment]
Those API calls haven't been lightning fast for me, which is why I know off the top of my head that clicking it makes one! 😅 But anyway that's probably off topic for this feature, which seems useful and reasonable (especially assuming the data is already there).

**Comment by thesunshade** [comment]
I guess ideally if an additional call is needed the notification could pop up after the page loads (which wouldn't be bad and might even be good).

I have also noticed that the new Voice icon gets added after the whole page loads.

**Comment by sujato** [comment]
Thanks for the suggestion, but I'm going to say no to this one.

SC has for many years supported and enabled people to read multiple translations, probably more than any other site. However I don't personally think this is very useful, and IMHO, based on twenty+ years of teaching suttas, when people "compare" translations they usually waste time with surface choices of the translators. Non-experts have no way of telling when a difference is due to a mistake and when it is simply a matter of taste. Better to have one good translation and refer to the source, or have some good notes or guidelines, or ask someone who understands the issues.

The main purpose of hosting different translations was simply because there was no single good source available for all the suttas. Now we continue to provide this service, but it is not a priority and not something we want to put time into.

What I would support is a genuinely targeted translation that has a specific and meaningful translation goal that is distinctively different than current translations. The obvious case would be a word for word literal translation (insofar as such a thing is possible). Other examples might be a deliberately more dynamic or poetic translation, or one focused on a specific cultural group. We need to start thinking about translations more strategically, rather than just, "I don't like how they translate sankhara!". 

And finally, to concur, we shouldn't be adding complexity to the front end and additional tasks for coders. I'd be much more interested in spending time optimizing, debugging, and improving performance and reliability!

**Comment by thesunshade** [comment]
This feature is now available in the Browser extension:

https://discourse.suttacentral.net/t/a-browser-extension-for-suttacentral/36074

**Comment by agilgur5** [comment]
For reference, back linking this issue to its [corresponding forum thread](https://discourse.suttacentral.net/t/suggestion-add-notification-if-there-are-multiple-translations/23152?u=agilgur5)
