### ISSUE TITLE
Font styling does not work well for some languages

### ISSUE THREAD

**Issue by sabbamitta** [suttacentral/suttacentral#3240]
Based on the feedback of the Korean interface translator @gloine I am describing this issue here. I don't know what the solution can be, or if there can be any solution at all.

Quoting from a conversation on D&D:

> I have a number of suggestions for better Korean site readability. Koreans rarely use italic fonts, so it is better not to use them. For example,
> 
> ![grafik](https://github.com/user-attachments/assets/d519d254-d0f5-4e81-96a4-433c8f9e488a)
> 
> This one immediately tells koreans this site is not Korean native, thus not friendly. Could we do something about it?
> 
> Also, there are some font size issues:
> 
> ![grafik](https://github.com/user-attachments/assets/3e406424-5677-4a85-9763-215d27974eff)
> 
> Font size is too small for the first menu line and the 티피타카(삼장) line, too.
> 
> Capitalized words in English look bigger and that’s basically the issue here. Both the menu and main title lines are capitalized. Unfortunately there is no capital letter in Korean :frowning:

**Comment by thesunshade** [comment]
The i18n styles are here: [/suttacentral/client/elements/styles/sc-typography-i18n-styles.js](https://github.com/suttacentral/suttacentral/blob/main/client/elements/styles/sc-typography-i18n-styles.js)

It seems the specific instructions to ignore the italics is being ignored. So that is indeed a bug.

**Comment by sabbamitta** [comment]
Thanks, that is helpful!

**Comment by thesunshade** [comment]
This is a possibly related issue: https://github.com/suttacentral/suttacentral/issues/3002

**Comment by sujato** [comment]
Thanks!.

As for the italics issue, as pointed out, the problem is that the existing directive `font-synthesis: none` is not being applied. 

Using it the italics go away:

![Screenshot from 2024-08-17 16-20-31](https://github.com/user-attachments/assets/658c7d03-ae3a-45e8-bbff-79d9f7b55577)

Caniuse says `font-synthesis` now works in 94% of browsers, so that should be all we need.

- [x] Make sure that `sc-typography-i18n-styles.js` is actually applied and working. 

As for the font size issues, the image is really too small for me to make out much. But to me it doesn't look too bad on the site. Let's fix the i18n-styles first then see how it is.
