### ISSUE TITLE
Structuring the Dhammapadas

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#817]
Original ticket Creator:
sujato.bhikkhu

One of the major issues we have is how to present the Dhammapadas in a coherent and consistent manner. Here are my current  thoughts on the matter.

The Dhammapadas present a number of challenges, as there are several of them, each with its own quirks, and many parallels. Even though the texts are closely related, they are organized differently in our files (unlike say the patimokkhas), reflecting the complex textual lineage that has brought them to us.

Here are the different structures.
h3. 1. One big blob

Pali Dhammapada (dhp) is just  one HTML file, with referencing solely by verse number. Vaggas are present, and are significant to the text, as they organize verse by topics. The problem here is that it's quite common to refer to the verses informally by vagga (as say "the chapter on flowers), but the formal referencing is almost always by plain verse number, which we adopt. So currently we have no representation of vaggas, and the whole thing appears as one suttaplex. This is clearly untenable, as there's thousands of parallels included in one suttaplex.
h3. 2. Vaggas in Suttaplex

The Chinese Dharmapadas (t210, t211, t212, t213) as well as the Sanskrit Udanavarga (uv) are represented by a single entry in the sidebar, with the suttaplexes listed by vagga. Within each vagga, the parallels appear as sectional parallels. This results in a sane size of suttaplex list (under 50 suttaplexes), and also a sane number of parallels per suttaplex (usually a hundred or so). Also, the suttaplex titles are meaningful. But it lacks the ability to navigate in the sidebar by vagga, which we can do everywhere else.
h3. 3. Vagga in sidebar

Pdhp and gdhp list the vaggas in the sidebar, and the suttaplexes are per verse. So this is pretty much like a standard collection, except one verse = one sutta. The problem is that this results in long suttaplex lists, which are not very informative. The verses don't really have titles, so you've got a bunch of mostly space-wasting suttaplexes.
h3. So what to do?

I think the ideal solution would be to combine 2 and 3. That is:# Represent vaggas in sidebar# Present suttaplexes per vagga

In this case, if you clicked on a vagga in the sidebar, you'd get a suttaplex list consisting of just one suttaplex. That's okay. 
h3. Also, let the Dhammapadas be friends!

Since these are a tightly linked group of texts, it would be nice to collect them together. On Discourse I suggested (https://discourse.suttacentral.net/t/overall-text-hierarchy-for-sc-next/6101/27) we have one menu item "Dharmapadas", and there include all the Sanskritic and Chinese Dharmapadas.

It would be nice to include the Pali there as well. Unlike the others, though, the Pali has a strongly defined place in a structured canon, and we must keep it there in KN. But perhaps we could duplicate the entry, and present it in the Dharmapadas list as well? I'm not sure how hard this would be technically, but if it's straightforward, let's do it.

Jira ID: SUCE-455
Jira Creation Date: 13/Jan/18 11:32 AM
Jira Epic: 
Jira Priority: Medium
Jira Status (at import): Selected For Development

Comments:

**Comment by SamaneriVimala** [comment]
Let me know if this is okay. I've done it the same way as the Dhammapada.

**Comment by sujato** [comment]
Okay, well I agree it could be better, but at least it is working! Everything is there, and while not 100% consistent, at least its pretty much sane. So that's not nothing.

The decision during the development process was that parallels in Dhp-style texts should be per-vagga. The reason for this is that there are no titles or other info for verse. A "card" is really designed to present more information than just a set of parallels. So if they are per-vagga the parallels are there with less "overhead" so to speak. 

The only drawback I can see to this system is if there are simply too many parallels in one vagga. Currently the upper limit seems to be about 200, which is a lot, but I think it is workable. I takes a few seconds to load 200 parallels on my machine, and they are quite convenient to scan. 

So unless there is some problem I am missing, let's stick to **parallels per vagga**.

We should **list the vaggas in the sidebar** also, as this is standard practice in the texts.

Then the presentation of the text would depend on how it is structured. 

- **If the whole text is in one file, then there is an extra suttaplex at the start** (like the Pali Dhp).
- **If the text of each vagga is in a separate file, then each suttaplex has its text** (like with uv).

***

There are a few other issues, which I'm not sure if they belong in other tickets.

1. The ID for Udānavarga should be Uv, not UV. The general rule is that if a word is usually spelled separately it is capitalized. But the -varga suffix is usually compounded, so it should be lower-case. Currently this is missing from our Abbreviations page, so it should be added there. 
  - As a consequence, Udanavarga de Subhasi should be UvS.
2. The ID for the Tibetan text is not consistent. In the URL it is xct-uv, but in the suttaplex it is Uv Kg. The acronyms and IDs must always be simply different forms of the same thing. It seems Uv Kg is taken from U Oslo, right? In that case, stick to that.
3. What's up with T211? There's no parallels appearing.
4. Each of these texts should have a blurb. This should appear in the suttaplex (where the whole text is in one file) or in the node (if the text is divided into vaggas). I'll write blurbs for the missing ones.

**Comment by SamaneriVimala** [comment]
> The only drawback I can see to this system is if there are simply too many parallels in one vagga. Currently the upper limit seems to be about 200, which is a lot, but I think it is workable.

There are vaggas with 300 items and I have not finished uploading all the parallels yet so there might be more.

> We should list the vaggas in the sidebar also

That would mean that for each vagga you only get one suttaplex card when you click on it.

So in light of the comments above, before I do this I want to be absolutely sure that you want this (it's a bit of work so I don't want you to go: well, that's not what I meant, lets change it again):

So to summarize what I understand you are staying:

1. Main title in sidebar: Dhammapada (or Patna Dharmapada, etc.) with an expander.

1. Click on the main title and you get a suttaplex with the text, blurb, translations, etc. and underneath the suttaplexes for each vagga.

1. Open the expander in the sidebar and it shows all the vaggas with numbers. (but it does not show where to click for the text, so no "Dhammapada full text" item at the top of the vagga-list.

1. Click on the vagga name and you get one suttaplex for that vagga.



> There are a few other issues, which I'm not sure if they belong in other tickets.

Probably, but I fixed them anyway.
T211 only has parallels for vagga 31 and 38

> Each of these texts should have a blurb. 

Will put them in when you write them. I've make a new ticket for that and assign it to you. It's issue #978

**Comment by sujato** [comment]
Okay, so on review, I'd like to change the approach a little. I think we should get rid of the idea of having separate suttaplex cards for the whole text and then the vaggas. It's mixing up levels in a confusing way.

Instead, let's do the following.

## Use the current Udānavarga presentation as template

Currently the Udānavarga uses the following method.

1. The text title is in the sidebar.
2. The text title and blurb are in the top-level node.
3. One suttaplex per vagga.

That seems pretty good and sane to me. Several other Dhammapadas follow a similar method. So let's apply the same principles to all the Dhammapadas. They will have to work a little differently under the hood, depending on whether the text is in one file or many, but the UI should be the same for the user.

## To vagga or not to vagga?

Then there is the question as to whether to have the vaggas in the sidebar. This doesn't heavily affect users, as it is merely a different way of navigating the same thing. The advantage is that the sidebar is more compact, so you can go straight to a vagga if you know what you want. Still, either way would really be fine. The main thing ATM is that we have a consistent and predictable interface.

I would say this depends on how much time it'll take to code. Assuming that having no vaggas is simplest, let's get that happening. If we have the time and interest, we can consider adding vaggas to the sidebar later. Does that sound reasonable?

## G2dhp and G3dhp

For these, just list the whole text in the suttaplex, rather than parallels per verse.

**Comment by SamaneriVimala** [comment]
I've made some tests so please have a look.

1. All DHPs are now as per vaggas. Only for GDhp I added the vaggas to the sidebar also as a test, but I don't really like it: it adds too many headers in the suttaplex view. 

1. The parallel links no longer work in this but I don't want to change that until I know this is what we want.

1. G3Dhp has 512 parallels so takes ages to load (actually, my browser crashed on it). Any ideas how to solve this?

**So I suggest the following:**

Vaggas in sidebar: leave them out. There are only max 26 vaggas or so and that is easy enough to find in the suttaplex list. IF we put the vaggas in the sidebar, then also add the verse numbers before them.

G3Dhp: make some kind of vagga-subdivision.

**Comment by SamaneriVimala** [comment]
With regards to G3Dhp, I've made it into 9 sections of 10 verses so it no longer crashes.
Issue #1012 is done.

**Comment by sujato** [comment]
This is looking great! I agree, let's leave the vaggas out of the sidebar. Apart from the issues you have noted, we can go ahead doing it this way.

**Comment by sujato** [comment]
I didn't realize the Pali Dhp would be actually split into vaggas. Hmm, this is good for reading, but bad for simple and predictable URLs. Let's discuss this some more.

**Comment by SamaneriVimala** [comment]
Just the same as Udanavarga. It's the same for the URL. Check out any parallels-page in the suttaplex and click on the link below the dhp number - it will highlight the dhp number.
(I don't think this was updated to staging yet so use local)
