### ISSUE TITLE
Add Nakatani's 1987 Udanavarga de Subasi

### ISSUE THREAD

**Issue by Aminah-SC** [suttacentral/suttacentral#890]
PDF [available here](https://github.com/suttacentral/suttacentral-files/blob/master/Nakatani_1987_Udanavarga_de_Subasi_1.pdf)

- [x]  Prepare / extract / OCR text
- [x] Clean & code (Examples of coded [varga 1](https://drive.google.com/file/d/1hd_QTMia5KXJ9AoV41e_TREWwSVJV7Em/view?usp=sharing) and [varga 2](https://drive.google.com/file/d/1ueFhyaXnj6Qcw475RtkJPxI37yPanB7y/view?usp=sharing))

#### More info 

* There is a difference between the verse number in the present edition and the ones in the manuscript. The present edition numbers are the big bold numbers at the start of each verse which we will not use.

* Note that all the dots, parenthesis, slashes, pluses and whatnot are also part of the text. These have to be coded in a specific way because they have special meanings in such texts. See for instance the [Gāndhārī 3rd Dharmapada](https://legacy.suttacentral.net/gr/g3dhp).

* (Unlike the Gāndhārī 3rd Dharmapada) each varga is to be chopped into separate files; see eg the [Udanavagga](https://suttacentral.net/uv). In fact, the Udanavagga appears to have the same headings as the Udanavarga so we stick to the same numbering.

* _The specifics of how to treat various details will become clearer during the process._

**Comment by Aminah-SC** [comment]
Hullo @SamaneriVimala, [Here](https://drive.google.com/file/d/1P5EBeaWA4aXyJm6Fp21M0wuoAQzniBmH/view?usp=sharing) is the extracted / OCRed text. It's not perfect, but is probably much preferable to typing it out from scratch. Do you want to have a scan through it before I start coding?

**Comment by SamaneriVimala** [comment]
@Aminah-SC Thanks for that!
Please note that I have already done chapters 1 and 2 and part of 3 here:
https://github.com/suttacentral/sc-data/tree/master/html_text/san/sutta/uvs

I had a look at the file and it is not bad and will certainly make things much easier, but please check each and every line because I did see mistakes in just about every one of them. You can do some regex magic to set up the basic coding, but will still need to check each character.

**Comment by Aminah-SC** [comment]
Okay, great, I'll start playing with that. Good to know, part of 3 is done, too. I thought it was only 1 & 2. 

Re the meta area, I've just copied what you had for the first two files in the 'shell' varga files I've created. Of course, changes can be regexed as needed. 

Beyond that, I can't readily see how I might use regex here; I was thinking along the lines that Emmet would be my bestest buddy for this one (but if you've got better ideas please share :D).

**Comment by SamaneriVimala** [comment]
ehhh ... Emmet??? Never met him, I'm afraid!

**Comment by Aminah-SC** [comment]
:laughing: 

https://emmet.io/
Very brief overview: https://youtu.be/HuP5HDtPbYE?t=48

Waaaay too late in the process of preparing the Russian files I discovered custom snippets and it sped things up hugely.... just have to blow the dust off my brain to remember how I did it now. ;-)

**Comment by Aminah-SC** [comment]
I used it for wrapping... basically everything, headings, ps, blockquotes, lists, spans... whatever... I'm presently being bamboozled by the funky way lookbehinds work (or more to the point, don't), but can follow up on Stride a bit later if you like...?

**Comment by Aminah-SC** [comment]
A few handling Qs, @SamaneriVimala :pray: 

### 1
 
Some chapters end with some special marking, eg verse 82 that closes varga VII (pdf page 26): 

> (ma 7 / / */ /)

Are they to stay in? If so will they be given the `gap` class (like the other slashes in the already coded files)? Also if so, will the numbers they include be left in (there are so many reference numbers I can't say I have a clue what _any_ of them refer to, but on the face of it these numbers seem to belong to the same set that have been remove from the end of all other stanzas). 

### 2

There are a few places (eg. verse18, pdf p.14) were the hnfolio reference is given as:
> 5r4/5

Is there any problem with putting the idea as such or should the "/" be changed? 

### 3

There are a few places (eg. verse232, pdf p.51 & v266, pdf p.57) where the reference info deviates from the standard pattern. Respectively:

> [15; 16]  &  [20?] 

What `id`s should these kinds of things be given?

**Comment by SamaneriVimala** [comment]
First of all, you can use whatever your want of course but I think the coding should overall be fairly simple to do with regex and if you add a `<split>` tag in between the chapters before each header, I can give you a python program that then converts it to separate files with the correct filenames based on the section id. But up to you of course. This one is not too big to do the splitting manually.

As for your questions:
verse 82 ending: The '/' denote 'intervalle marquant la fin de padayuga.' (i.e. class="gap"), so that should stay in. Looks like the whole lot is in brackets anyway so that would mean a supplied-class. The star is the only thing I'm uncertain about. It seems to appear at the end of vaggas.
I would leave it in and code it as:
`<span class="supplied>ma 7 <span class="gap">/ / */ /</span></span>`

hnfolio numbers: probably best to make it 5r4-5

Verses with other numbers: I have not used the numbers between brackets at all but the fat numbers at the end of each verse. So verse 232 would be `<a class="uvs" id="18.16"></a>`
The numbers between brackets are "renvoient aux stances correspondantes dans l'Udiinavarga, édition Bernhard" so these are corresponding verses and are only of concern to me, who will take care of adding the parallels after these texts have been uploaded.

**Comment by Aminah-SC** [comment]
Much thanks!

I already split them yesterday, but for the future the python splitter (as well as, perhaps an explanation for those of us still in technical infancy :grin: ) sounds absolutely awesome!

> I have not used the numbers between brackets at all but the fat numbers at the end of each verse.

Bananas! It looks like I confused which numbers you used in your examples, because the ones in the square brackets in the first chapters are exactly the same as the bold numbers (Pity! The text extraction includes the squares and excludes the bold ones and I've some lovely regex to get the refs correctly coded - ah well, the whole thing needs almost character by character correction so no harm in a few more). 

Following on from this then, in eg. v22 the fat number is "1(7)". A quick scroll shows that his happens in a few other places. I'm guessing the ID would be given as "17"?  

As another follow on: v121, v269 & v576 seem to be "extra" verses in that they don't have fat numbers. What should their 'uvs' IDs be? 

And one final follow on: eg. v268 two fat numbers are given, which should be used? (I'm not sure how many instances of this there are).

Also, just to be super, crispy clear, "7 / / */ /" does not need to be coded as one unit? I understand this as denoting "here is the end of chapter 7" (I don't know why it isn't used for the first 6 chapters, but going forward it appears to be used in this way).

**Comment by SamaneriVimala** [comment]
> Following on from this then, in eg. v22 the fat number is "1(7)". A quick scroll shows that his happens in a few other places. I'm guessing the ID would be given as "17"?

Yes, it seems like 17 is correct.

> As another follow on: v121, v269 & v576 seem to be "extra" verses in that they don't have fat numbers. What should their 'uvs' IDs be?

These are Uddana verses. They don't need a number but you can code them as `<p class="uddana">`. They appear after the closing of a sutta. 
But the line above, for instance `krodha-varga (vlsati) 20 / /` is not part of the previous verse either. This can just be coded in it's own `<p class="endvagga">`

Come to think of it, the earlier mentioned example about the m7 should also be on it's own line and should become:
`<p class="endvagga"><span class="supplied>ma 7 <span class="gap">/ / */ /</span></span></p>`

> And one final follow on: eg. v268 two fat numbers are given, which should be used? (I'm not sure how many instances of this there are).

No, they are two different things. The first is the verse number 17 and the line below is not part of the verse but an endvagga too before the Udana.

>  "7 / / */ /" does not need to be coded as one unit?

Not sure what you mean here. The slashes are clearly gaps in the manuscript but the end part just mentions the number of the vagga it refers to. I think the previous vaggas were not done that way because the last verses of each vagga there seem to be missing. So the missing verses I have put in as `<p class="add">[Stances 16–17 perdues]</p>` on their own line.

**Comment by SamaneriVimala** [comment]
Just to make things super confusing (but don't look if you don't want to: everything I added above is what is needed); here is a file with all the various possible tags you can use:
https://suttacentral.net/zz3/zz/test (Text classes)
https://suttacentral.net/zz1/zz/test (Textual Info classes)
