### ISSUE TITLE
Migrate to new mapping platform

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#939]
## what we have

Currently SC serves maps as part of search results. If you search for an included place name, a map with the location is presented in the search results:

https://suttacentral.net/search?query=savatthi
https://suttacentral.net/search?query=vesali

If you click through to the full dictionary definition page, it is also there:

https://suttacentral.net/define/s%C4%81vatth%C4%AB
https://suttacentral.net/define/ves%C4%81li

The place searched for should appear in the center of the map.  

Features include:

- full screen
- sharing link
- zoom/pan
- sidebar with list of places
- sidebar with detailed entry for place names.
- icons for different kinds of places (cities, forests, etc.)

## the problem

Currently this uses the free google custom maps service. This has a number of problem, mostly the fact we are exposing our users to surveillance and tracking. But also, it's not a very attractive widget, and the presence of all the modern mapping details makes it hard to see what we're looking for.

## the solution

We should migrate to a new mapping platform, with the following aims:

- no using Google maps or other surveillance-happy services
- make it look nice
- don't display modern names and features, only what we have defined and possibly geographical features
- better icons
- use a light-weight library
- integrate well with the SC approach, i.e. use web components, and lit.
- don't lose current functionality (this is a nice-to-have; if some features are too hard to replicate we can reconsider)
- add cool new features?

We do not have to replicate the sidebars, in fact I don't particularly like them. But we should have the features available somehow.

- there should be a list somewhere of all the places in the map. 
- we should be able to access the extra info somehow

Probably best to look at how this is handled in the different libraries and find a solution that works in the way our chosen library wants to work.

The data is in KML, which is a mapping standard, so it should be portable, at least in theory. Here it is:

[buddha-india.zip](https://github.com/suttacentral/suttacentral/files/8240767/buddha-india.zip)

## how to do it

We don't have a decision on what solution to use. This will be up to the developer, but here are some options.

An interesting new approach is to get maps adopted as HTML.

https://github.com/Maps4HTML

This is of course very much in tune with the web components philosophy, and the peeps in question have in fact built a web component.

https://maps4html.org/web-map-doc/

Maybe this is the right fit for us?

Meanwhile, a good solution seems to be Leaflet.js:

https://leafletjs.com/

40kb: https://bundlephobia.com/package/leaflet@1.8.0

This seems like it might be a good fit:

https://openlayers-elements.netlify.app/#/elements/ol-layer-openstreetmap/demos/standard-map

It uses lit-element. It's 70kb: https://bundlephobia.com/package/ol@6.14.1

Also this one is built on leaflet.js by a prominent member of the lit community. But it hasn't been developed for a few years.

https://www.npmjs.com/package/leaflet-element

**Comment by thesunshade** [comment]
With the current embed, there is the feature of clicking on this 
![image](https://user-images.githubusercontent.com/82448383/158713518-e30826bb-3aae-49a1-9321-122c3b84ef0e.png)

to get a larger map, e.g.:

![image](https://user-images.githubusercontent.com/82448383/158713570-55718888-a658-4802-b62e-fb3a02ef4a42.png)

And then clicking on an item gives more detail:

![image](https://user-images.githubusercontent.com/82448383/158713871-312eaa50-cf14-4556-a94a-25df614dfa9b.png)


Is that functionality that you hope to replicate?

**Comment by sujato** [comment]
Yes. We should have a "full screen" option, and also a way of viewing the extra info.

**Comment by MareinK** [comment]
I've had a look at alternative mapping solutions. Partly I'm just confirming what @sujato has said.

### Imagery source
One part of a mapping solution is the imagery source - a server which provides the graphical map tiles. For Google Maps, this is obviously Google itself, but there are others sources. In my experience, the most popular and complete alternative for map data is OpenStreetMap (OSM), which is used by all of the possible solutions that @sujato has listed. Since you did not mention the imagery source, perhaps it is obvious that we will be using an OSM solution, but I just wanted to make that explicit here as a choice.

Note that although OSM has served me very well in Europe (personally and in web apps), I don't have any experience with it in India. The map on [this page](https://wiki.openstreetmap.org/wiki/Completeness) suggests that data coverage in India is relatively low. I had a look for alternatives specific to India and didn't find any that are good, free, and open-source, so I still think OpenStreetMap is the best option.

If we want to add satellite imagery as well (not currently a feature), we would have to choose an additional imagery source for that (since OSM only supplies maps) and in that case it would be helpful if we choose a solution now which supports such a source.

### Data format
@sujato mentions KML as a data format. I think this format is quite specific to Google and it's not supported by many other solutions. In particular the alternative solutions listed do not seem to support KML. Instead, GeoJSON seems to be the way to go, and it's supported by the listed solutions. It should be easy to convert from one to the other using an existing tool.

### Choice of solution
To me [Leaflet](https://leafletjs.com/) seems like the obvious choice. It is very well-developed and popular, and it supports many of the features that we want out-of-the-box. It is also very extensible for other features (with [many plugins](https://leafletjs.com/plugins.html) already available), which is probably a good way to implement features like the sidebar and other useful things. As indicated, it has a small filesize. It supports adding a satellite layer if desired.

The downside is that Leaflet is not itself a web-component. As @sujato showed there is already [at least one project](https://www.npmjs.com/package/leaflet-element) to wrap it as one, but I'm not sure how easy it is to use (custom) plugins with that project (I can't find any references to it in the documentation) and to build our required features. But we could give it a try and investigate further.

Perhaps it's an option to build our own component around Leaflet, but I'm not yet familiar enough with this project to judge that. (for my own documentation, [here](https://stackoverflow.com/questions/66600326/leaflet-usage-in-litelement) is a minimal example I found).

The two other listed options ([Maps4HTML](https://maps4html.org/web-map-doc/) and [OpenLayers](https://openlayers-elements.netlify.app/#/elements/ol-layer-openstreetmap/demos/standard-map)) seem to me to be not very well-developed yet and maybe not allow enough customization.

### Where is the map code now?
I've been trying to find the current Google Maps embed code, but weirdly I've not been able to. I was expecting to find it for example somewhere in [`sc-page-search.js`](https://github.com/suttacentral/suttacentral/blob/master/client/elements/sc-page-search.js), but actually I can't find references to Google Maps anywhere in the code (except for stylesheets). However the map does render successfully in my local env.

**If someone could give me a pointer to how/where the map element is rendered at the moment, that would be great!**

**Comment by sujato** [comment]
Hey thanks for the nice summary and feedbaclk!

Just to confirm what you say about OSM and geoJSON. 

Also, with the leaflet-element, it was made by Benny Powers, who is a very friendly and helpful chap. You can contact him on twitter, but the best place would be the Lit slack: https://join.slack.com/t/lit-and-friends/shared_invite/zt-1bi5o5hs4-zyJdJuxLUOKmyzWCoBxnGw 

As for the location of the maps stuff, best ask on gitter.

**Comment by thesunshade** [comment]
> I was expecting to find it for example somewhere in [`sc-page-search.js`](https://github.com/suttacentral/suttacentral/blob/master/client/elements/sc-page-search.js), but actually I can't find references to Google Maps anywhere in the code (except for stylesheets).

Are you looking for this file?
https://github.com/suttacentral/sc-data/blob/master/dictionaries/complex/en/pli2en_dppn.json

I believe that is where the data for each location is stored.

**Comment by sujato** [comment]
Yes, I believe that's it, the google maps call is simply hard-coded in the place names in dppn

**Comment by MareinK** [comment]
Thanks @sujato and @thesunshade. As indicated on Gitter, that is the file I was looking for. I didn't find it because: 1. GitHub search didn't search the file because of its size, and 2. it didn't show up when searching my working dir because the `sc-data` folder is a nested docker volume, which is not propagated.

Anyhow, I thought that a good first step would be to **lift the map implementation from the data repo to the client code**. This prevents the problem I was having and also makes working on the map implementation much easier. To that end, I created two pull requests which, if approved, should be accepted in this order:

1. suttacentral/suttacentral#2474
2. suttacentral/sc-data#143

This should bring no changes in functionality or visuals, except:

- In both places where a map can be shown (search page and dictionary page) the margins are now equal (namely `--sc-size-md`, while search used to be `--sc-size-md-larger`). I'm not sure if this is desired, but it does improve visual consistency and reduces code complexity.

I look forward to hearing your feedback on this proposal!

**Comment by MareinK** [comment]
Just to document some data:

I noticed the kml file included in the original issue seems outdated compared to the full Google map on SC right now. Here is a new export which I am using as basis for the new map right now: [buddha-india.zip](https://github.com/suttacentral/suttacentral/files/9082652/buddha-india.zip).

I also found that most kml->geojson converters exclude a lot of important information that is in the kml, but [mapbox's togeojson](https://github.com/mapbox/togeojson) preserves nearly all information, and specifically [this fork](https://github.com/FBrusquetti/togeojson) also includes the layer information which we need. So after forking that fork and updating with the upstream changes from mapbox, I used it to convert our data and produce a geojson file: [map-data.zip](https://github.com/suttacentral/suttacentral/files/9082821/map-data.zip). There is some superfluous information in it now that only made sense in the Google maps context, so there will probably be another cleaned version later.

**Comment by MareinK** [comment]
The geojson data contains a bunch of properties which need to be implemented in the new map, or removed if they are superfluous. Below I have a checklist to keep track of which properties have been dealt with:

- [ ] `layerName` - should probably be used to construct something analogous to the old sidebar pane, where all features are listed
- [ ] `name` - should probably be visible on mouse-over and/or clicking, as a popup
- [ ] `styleUrl` - seems to be google-specific
- [ ] `styleHash` - seems to be google-specific
- [ ] `icon` - should be visible on the map, however the current icons (URLs) are hosted by google. We probably need to choose new&free&open icons
- [ ] `description` - should probably be visible on clicking, as a popup
- [ ] `gx_media_links` - seems to be google-specific
- [ ] `styleMapHash` - seems to be google-specific
- [ ] `stroke` - should be visible on the map
- [ ] `stroke-opacity` - should be visible on the map
- [ ] `stroke-width` - should be visible on the map
- [ ] `fill` - should be visible on the map
- [ ] `fill-opacity` - should be visible on the map

Additionally I'm thinking about adding new properties:

- [ ] `id` - a unique ID for each feature, which can be used to make map elements that are focused directly on the feature rather than on the latlng coords. Among other uses

**Comment by MareinK** [comment]
Since my last comment I have made a lot of progress on the new map element. Below is what the element currently looks like on a search/dictionary page. The marker relevant to the displayed page is highlighted. 

![image](https://user-images.githubusercontent.com/1388357/202235343-c9e962ad-7ea4-4667-b1fe-78c993a9dbf6.png)

Another image of the element, this time on a page related to a region rather than a point. When mousing over any feature, its name is shown. Clicking on a feature takes the user to the page related to that feature (if available).

![image](https://user-images.githubusercontent.com/1388357/202235603-7f856890-3815-4299-b414-b114a0d84192.png)

The button on the top right takes the user to the static map page, shown below. 

![image](https://user-images.githubusercontent.com/1388357/202235957-44ac5893-4174-4967-9cc8-4e951845f7bc.png)

The second top right button allows turning on/off specific layers.

![image](https://user-images.githubusercontent.com/1388357/202236267-496058ea-a89f-47c9-a413-c090cd45406b.png)

There is the possibility to have links to the static map page in various menus.

![image](https://user-images.githubusercontent.com/1388357/202236518-dffb21e8-d6f8-451f-b76e-9cf8030937e8.png)
![image](https://user-images.githubusercontent.com/1388357/202236577-d13e8776-3699-4c8a-81fb-6530c8a4089e.png)

At one point I implemented an information pane that was shown when clicking a feature, but I found that the 'extra information' that was associated with the different map features was actually almost identical to the information on the corresponding definition pages for those features. So for the time being I have stripped that extra information from the data, and just like through to the definition pages.

Possible improvements:

- [ ] Better icons for point features
- [ ] Improve display of icons in the list on the static map page
- [ ] Restore some things that were lost in the 'extra information' (images, and info for features that do not have a corresponding definition page)
- [ ] More?

**Comment by sujato** [comment]
It's looking good, let's close this issue, and we can put any further items on a new issue.
